In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import re
import ast
import pickle

import numpy as np
import pandas as pd
import seaborn as sns

import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import warnings

warnings .filterwarnings('ignore' )

In [ ]:
 movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [ ]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [ ]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies.shape, credits.shape

((4803, 20), (4803, 4))

In [ ]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [ ]:
movies = movies.merge(credits, on ='title')
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
movies[['movie_id','title','overview','genres','keywords','cast','crew']][:2]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
df = movies[['movie_id','title','overview','genres','keywords','cast','crew']]
df.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
df.shape

(4809, 7)

In [ ]:
df.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
df['overview'].fillna(' ', inplace=True)

In [ ]:
df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
df['genres']

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...
4804    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4805    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4806    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4807                                                   []
4808                  [{"id": 99, "name": "Documentary"}]
Name: genres, Length: 4809, dtype: object

In [ ]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
type(df['genres'][0])

str

In [ ]:
ast.literal_eval(df['genres'][0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [ ]:
for i in ast.literal_eval(df['genres'][0]):
    print(i['name'])

Action
Adventure
Fantasy
Science Fiction

In [ ]:
def fetch_genres(obj):
    l = []
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [ ]:
fetch_genres(df['genres'][0])

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [ ]:
df['genres'].apply(fetch_genres)

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...
4804                        [Action, Crime, Thriller]
4805                                [Comedy, Romance]
4806               [Comedy, Drama, Romance, TV Movie]
4807                                               []
4808                                    [Documentary]
Name: genres, Length: 4809, dtype: object

In [ ]:
df[:2]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [ ]:
df['genres'] = df['genres'].apply(fetch_genres)

In [ ]:
df[:3]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
df['keywords']

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...
4804    [{"id": 5616, "name": "united states\u2013mexi...
4805                                                   []
4806    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4807                                                   []
4808    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4809, dtype: object

In [ ]:
df['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [ ]:
def fetch_keywords(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [ ]:
fetch_keywords(df['keywords'][0])

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [ ]:
df['keywords'].apply(fetch_keywords)

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4809, dtype: object

In [ ]:
df['keywords']

0       [{"id": 1463, "name": "culture clash"}, {"id":...
1       [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2       [{"id": 470, "name": "spy"}, {"id": 818, "name...
3       [{"id": 849, "name": "dc comics"}, {"id": 853,...
4       [{"id": 818, "name": "based on novel"}, {"id":...
                              ...
4804    [{"id": 5616, "name": "united states\u2013mexi...
4805                                                   []
4806    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4807                                                   []
4808    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, Length: 4809, dtype: object

In [ ]:
df.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
df['cast']

0       [{"cast_id": 242, "character": "Jake Sully", "...
1       [{"cast_id": 4, "character": "Captain Jack Spa...
2       [{"cast_id": 1, "character": "James Bond", "cr...
3       [{"cast_id": 2, "character": "Bruce Wayne / Ba...
4       [{"cast_id": 5, "character": "John Carter", "c...
                              ...
4804    [{"cast_id": 1, "character": "El Mariachi", "c...
4805    [{"cast_id": 1, "character": "Buzzy", "credit_...
4806    [{"cast_id": 8, "character": "Oliver O\u2019To...
4807    [{"cast_id": 3, "character": "Sam", "credit_id...
4808    [{"cast_id": 3, "character": "Herself", "credi...
Name: cast, Length: 4809, dtype: object

In [ ]:
df['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [ ]:
def fetch_cast(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            l.append(i['name'])
            counter += 1
        else:
            break
    return l

In [ ]:
fetch_cast(df['cast'][0])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver']

In [ ]:
df['cast'] = df['cast'].apply(fetch_cast)

In [ ]:
df[:3]

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [ ]:
df['crew']

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4804    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4805    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4806    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4807    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4808    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4809, dtype: object

In [ ]:
df['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [ ]:
def fetch_director(text):
    l = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            l.append(i['name'])

    return l

In [ ]:
fetch_director(df['crew'][0])

['James Cameron']

In [ ]:
df['crew'] = df['crew'].apply(fetch_director)

In [ ]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
df['overview']

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: overview, Length: 4809, dtype: object

In [ ]:
df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
df['overview'][0].split()

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.']

In [ ]:
df['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4809, dtype: object

In [ ]:
df['overview'] = df['overview'].apply(lambda x:x.split())

In [ ]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
def to_string_list(x):
    """Helper function to ensure elements are strings within a list."""
    if isinstance(x, str):
        return [x]
    elif isinstance(x, list):
        return [str(item) for item in x]
    else:
        return []

for col in ['overview', 'genres', 'keywords', 'cast', 'crew']:
    df[col] = df[col].apply(to_string_list)
df['combined_features'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [ ]:
print((df['overview'] + df['genres'] +df['keywords'] +df['cast'] + df['crew'] )[0] )

['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', '[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]', 'Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'James Cameron']

In [ ]:
df['tags'] = df['overview'] + df['genres'] + df['keywords'] + df['cast'] + df['crew']

In [ ]:
df.head()

,movie_id,title,overview,genres,keywords,cast,crew,combined_features,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[[{""id"": 1463, ""name"": ""culture clash""}, {""id""...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""n...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""nam...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send...","[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[[{""id"": 818, ""name"": ""based on novel""}, {""id""...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili...","[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
df = df[['movie_id','title','tags']]
df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [ ]:
print(df['tags'][0])

['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', '[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]', 'Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'James Cameron']

In [ ]:
df['tags'].apply(lambda x: [i.replace(' ',' ')for i in x])

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: tags, Length: 4809, dtype: object

In [ ]:
df['tags']= df['tags'].apply(lambda x:[i.replace(' ',' ')for i in x])

In [ ]:
print(df['tags'][0])

['In', 'the', '22nd', 'century,', 'a', 'paraplegic', 'Marine', 'is', 'dispatched', 'to', 'the', 'moon', 'Pandora', 'on', 'a', 'unique', 'mission,', 'but', 'becomes', 'torn', 'between', 'following', 'orders', 'and', 'protecting', 'an', 'alien', 'civilization.', 'Action', 'Adventure', 'Fantasy', 'Science Fiction', '[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]', 'Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'James Cameron']

In [ ]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
df['tags'].apply(lambda x:' '.join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bond’s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4809, dtype: object

In [ ]:
df['tags'] = df['tags'].apply(lambda x:' '.join(x))
df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [ ]:
df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
ps = PorterStemmer()
for i in['love', 'lover', 'lovers', 'loving', 'lovely']:
  print(f'{i} ---> {ps.stem(i)}')

love ---> love
lover ---> lover
lovers ---> lover
loving ---> love
lovely ---> love

In [ ]:
PorterStemmer()
def text_preprocess(text):
 new_text = []

 for i in text.split():
      lower = i.lower()
      new_text.append(ps.stem(lower))

 return" ".join(new_text)

In [ ]:
text_preprocess(df['tags'][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi scienc fiction [{"id": 1463, "name": "cultur clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}] sam worthington zoe saldana sigourney weaver jame cameron'

In [ ]:
df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}] Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [ ]:
df['tags'].apply(text_preprocess)

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4809, dtype: object

In [ ]:
df['tags'] = df['tags'].apply(text_preprocess)

In [ ]:
df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [ ]:
df['tags'][1205]

'a lone doctor who onc occupi an unusu lakesid home begin exchang love letter with it former resident, a frustrat architect. they must tri to unravel the mysteri behind their extraordinari romanc befor it\' too late. romanc drama mysteri [{"id": 520, "name": "chicago"}, {"id": 1731, "name": "writing"}, {"id": 2301, "name": "architect"}, {"id": 2964, "name": "future"}, {"id": 3667, "name": "time"}, {"id": 12436, "name": "architecture"}, {"id": 15021, "name": "mysteri letter"}, {"id": 40847, "name": "near future"}, {"id": 47023, "name": "first kiss"}, {"id": 191100, "name": "romant drama"}, {"id": 192966, "name": "passag of time"}] keanu reev sandra bullock shohreh aghdashloo alejandro agresti'

In [ ]:
cv = CountVectorizer(max_features=5000, stop_words='english')
cv

CountVectorizer(max_features=5000, stop_words='english')

In [ ]:
cv.fit_transform(df['tags'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 195426 stored elements and shape (4809, 5000)>

In [ ]:
vectors = cv.fit_transform(df['tags']).toarray()
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectors.shape

(4809, 5000)

In [ ]:
cosine_similarity(vectors)

array([[1.        , 0.8416873 , 0.65264908, ..., 0.55533223, 0.01855177,
        0.39379375],
       [0.8416873 , 1.        , 0.64219492, ..., 0.55481575, 0.        ,
        0.39452673],
       [0.65264908, 0.64219492, 1.        , ..., 0.42786599, 0.0562878 ,
        0.29870172],
       ...,
       [0.55533223, 0.55481575, 0.42786599, ..., 1.        , 0.02828427,
        0.27874926],
       [0.01855177, 0.        , 0.0562878 , ..., 0.02828427, 1.        ,
        0.06064784],
       [0.39379375, 0.39452673, 0.29870172, ..., 0.27874926, 0.06064784,
        1.        ]])

In [ ]:
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.8416873 , 0.65264908, ..., 0.55533223, 0.01855177,
        0.39379375],
       [0.8416873 , 1.        , 0.64219492, ..., 0.55481575, 0.        ,
        0.39452673],
       [0.65264908, 0.64219492, 1.        , ..., 0.42786599, 0.0562878 ,
        0.29870172],
       ...,
       [0.55533223, 0.55481575, 0.42786599, ..., 1.        , 0.02828427,
        0.27874926],
       [0.01855177, 0.        , 0.0562878 , ..., 0.02828427, 1.        ,
        0.06064784],
       [0.39379375, 0.39452673, 0.29870172, ..., 0.27874926, 0.06064784,
        1.        ]])

In [ ]:
df[:5]

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [ ]:
distance = similarity[0]
distance

array([1.        , 0.8416873 , 0.65264908, ..., 0.55533223, 0.01855177,
       0.39379375])

In [ ]:
sorted(similarity[0], reverse=True)

[np.float64(0.9999999999999999),
 np.float64(0.9034437204570136),
 np.float64(0.9027428883008348),
 np.float64(0.9019365452526242),
 np.float64(0.9003123430002361),
 np.float64(0.8981570169693702),
 np.float64(0.8979802266666134),
 np.float64(0.896184131128316),
 np.float64(0.8924264398244509),
 np.float64(0.8911968234435997),
 np.float64(0.8905868634810417),
 np.float64(0.8905126826847543),
 np.float64(0.8895922255186359),
 np.float64(0.8893776057664129),
 np.float64(0.8891155671573213),
 np.float64(0.8875254321815702),
 np.float64(0.885649523387772),
 np.float64(0.8854420040004312),
 np.float64(0.8853400791863889),
 np.float64(0.8852772466539196),
 np.float64(0.884473256271032),
 np.float64(0.8833951030593978),
 np.float64(0.8832564959821234),
 np.float64(0.88281120183691),
 np.float64(0.8827719975307856),
 np.float64(0.8818159734598636),
 np.float64(0.8816926681737702),
 np.float64(0.8814009638691878),
 np.float64(0.8811862002711985),
 np.float64(0.8805913057895309),
 np.float64(0.880143434800544),
 np.float64(0.879779907698176),
 np.float64(0.8792557292024767),
 np.float64(0.8789034353497396),
 np.float64(0.8788272841602857),
 np.float64(0.8787951670201131),
 np.float64(0.8787403683656181),
 np.float64(0.878468252850306),
 np.float64(0.8783764329858633),
 np.float64(0.8781494233637918),
 np.float64(0.8780092243440978),
 np.float64(0.8779877700037859),
 np.float64(0.8775288243291409),
 np.float64(0.8775122670253096),
 np.float64(0.8770898668625975),
 np.float64(0.8768181225201753),
 np.float64(0.8764241920894363),
 np.float64(0.8761275667945907),
 np.float64(0.8760903396273627),
 np.float64(0.8758612547123485),
 np.float64(0.8757873891204219),
 np.float64(0.8757527339796719),
 np.float64(0.8756690316829597),
 np.float64(0.8756092772439399),
 np.float64(0.8753183160543416),
 np.float64(0.8749758849642125),
 np.float64(0.8747058054042085),
 np.float64(0.8742390357578075),
 np.float64(0.8740033611345973),
 np.float64(0.8736031296758948),
 np.float64(0.8735936489535829),
 np.float64(0.8732945050896962),
 np.float64(0.8732093016470978),
 np.float64(0.8731018096068464),
 np.float64(0.8730391944368876),
 np.float64(0.8729942707362257),
 np.float64(0.8729037363547731),
 np.float64(0.8728784744011475),
 np.float64(0.8727821472315183),
 np.float64(0.8726850090140326),
 np.float64(0.872374265406781),
 np.float64(0.8722610522658281),
 np.float64(0.8720387103975634),
 np.float64(0.8720387103975634),
 np.float64(0.8720152280692308),
 np.float64(0.8715028592635907),
 np.float64(0.8712942650587262),
 np.float64(0.8712641911327355),
 np.float64(0.871025603322482),
 np.float64(0.8709186112580303),
 np.float64(0.8708582239863715),
 np.float64(0.8702921193985093),
 np.float64(0.8701552574593399),
 np.float64(0.8698285612745719),
 np.float64(0.8698045155674722),
 np.float64(0.8696535775982357),
 np.float64(0.8695231068074601),
 np.float64(0.869336876631727),
 np.float64(0.8693206290310417),
 np.float64(0.8691089165413999),
 np.float64(0.8690991515711951),
 np.float64(0.8690669102979753),
 np.float64(0.8688678496585921),
 np.float64(0.8688208444034459),
 np.float64(0.8688208444034459),
 np.float64(0.8683344836757608),
 np.float64(0.8682614281651118),
 np.float64(0.8681916286895672),
 np.float64(0.8681455162539514),
 np.float64(0.8680527756540638),
 np.float64(0.8678466554213811),
 np.float64(0.8676202619750386),
 np.float64(0.867432339342686),
 np.float64(0.8671286213066095),
 np.float64(0.8668684635337864),
 np.float64(0.8662991327367799),
 np.float64(0.8662603817238974),
 np.float64(0.8662401670600344),
 np.float64(0.8658611975529836),
 np.float64(0.865352155874049),
 np.float64(0.8652297084238368),
 np.float64(0.8649451756762204),
 np.float64(0.8648633486704036),
 np.float64(0.8648182516177941),
 np.float64(0.8647890362654685),
 np.float64(0.8646200478189278),
 np.float64(0.8643439424395689),
 np.float64(0.8641180434923176),
 np.float64(0.8640967030502926),
 np.float64(0.8635511908396529),
 np.float64(0.8631471815536194),
 np.float64(0.8628545897404774),
 np.float64(0.8626420349601289),
 np.float64(0.8625738177254476),
 np.float64(0.8624095017790313),
 np.float64(0.8621939257910253),
 np.float64(0.8619001674952272),
 np.float64(0.8617621840079032),
 np.float64(0.8615476151764779),
 np.float64(0.8609925150204788),
 np.float64(0.8607350333422086),
 np.float64(0.8607107592313537),
 np.float64(0.8606602867211889),
 np.float64(0.860401998999592),
 np.float64(0.8603329910236194),
 np.float64(0.8603073665108816),
 np.float64(0.8602936849485664),
 np.float64(0.8599450039166773),
 np.float64(0.8598223174446135),
 np.float64(0.8596998735770104),
 np.float64(0.8596079210052872),
 np.float64(0.8592287506820633),
 np.float64(0.8589590836919876),
 np.float64(0.8585885619373651),
 np.float64(0.8585086042065009),
 np.float64(0.8585006310898384),
 np.float64(0.8584405495941203),
 np.float64(0.8583071444837874),
 np.float64(0.8580921908082019),
 np.float64(0.8580764294964058),
 np.float64(0.8580492471554083),
 np.float64(0.8580194745680598),
 np.float64(0.8580030857349829),
 np.float64(0.8579664175191296),
 np.float64(0.8579664175191296),
 np.float64(0.8578981306451199),
 np.float64(0.8575107412820909),
 np.float64(0.8572566215609368),
 np.float64(0.8571967911071791),
 np.float64(0.85706359282839),
 np.float64(0.8569776298794848),
 np.float64(0.8569519946804782),
 np.float64(0.8569442408750981),
 np.float64(0.8568337498449855),
 np.float64(0.8565830663280116),
 np.float64(0.8564140141461212),
 np.float64(0.8563033283021974),
 np.float64(0.8561665239518984),
 np.float64(0.8560850224295267),
 np.float64(0.8559152824808861),
 np.float64(0.8558526078537348),
 np.float64(0.8558314195786746),
 np.float64(0.8557790679207863),
 np.float64(0.8557561228987914),
 np.float64(0.8556059286654353),
 np.float64(0.8555408598753311),
 np.float64(0.8555408598753311),
 np.float64(0.8555167386353155),
 np.float64(0.8555027840493487),
 np.float64(0.8555019543603556),
 np.float64(0.8553581214417935),
 np.float64(0.8552616926182919),
 np.float64(0.8552443011149499),
 np.float64(0.8552124835566224),
 np.float64(0.8551499337314478),
 np.float64(0.8550185414364472),
 np.float64(0.8549718331497534),
 np.float64(0.8548590169229845),
 np.float64(0.8546098958286888),
 np.float64(0.8546098958286888),
 np.float64(0.8545188513572822),
 np.float64(0.8544483231606683),
 np.float64(0.8544198360330295),
 np.float64(0.8543371793242517),
 np.float64(0.8542264907417261),
 np.float64(0.8540080979230156),
 np.float64(0.8540080979230156),
 np.float64(0.8539699277412729),
 np.float64(0.853726050246849),
 np.float64(0.8537135957745973),
 np.float64(0.8536724101520301),
 np.float64(0.8536649671382335),
 np.float64(0.8535892063295424),
 np.float64(0.8535774085928641),
 np.float64(0.8534626142622576),
 np.float64(0.853447771305113),
 np.float64(0.8533986649249531),
 np.float64(0.8533830504793924),
 np.float64(0.853325727204939),
 np.float64(0.8533112958772527),
 np.float64(0.8533068431197406),
 np.float64(0.8531798579320069),
 np.float64(0.8530917331723924),
 np.float64(0.8529073845440115),
 np.float64(0.8528230315930029),
 np.float64(0.8527502936107653),
 np.float64(0.8527411714187332),
 np.float64(0.852679886559963),
 np.float64(0.8524911230848737),
 np.float64(0.8524483980819206),
 np.float64(0.8524196065233043),
 np.float64(0.8523951183919982),
 np.float64(0.8517940640558468),
 np.float64(0.851501624434583),
 np.float64(0.8514787855727387),
 np.float64(0.8514152044900805),
 np.float64(0.8514152044900805),
 np.float64(0.8514084099476587),
 np.float64(0.8513421691196678),
 np.float64(0.8513192368096931),
 np.float64(0.8512845359320667),
 np.float64(0.8512400859131902),
 np.float64(0.851093230473647),
 np.float64(0.8510671530849578),
 np.float64(0.8509282155922891),
 np.float64(0.8508996883597315),
 np.float64(0.8507822666608064),
 np.float64(0.850732707222491),
 np.float64(0.8503592128393512),
 np.float64(0.8502588342200641),
 np.float64(0.8500813846348964),
 np.float64(0.8500245882194715),
 np.float64(0.849372622088587),
 np.float64(0.8493678313241004),
 np.float64(0.8492757374707929),
 np.float64(0.8491463612433312),
 np.float64(0.8490315531755322),
 np.float64(0.8486950211653447),
 np.float64(0.8486463628844454),
 np.float64(0.8484273926523451),
 np.float64(0.848374772992278),
 np.float64(0.8483027707264547),
 np.float64(0.8482104939606733),
 np.float64(0.8480861731620588),
 np.float64(0.8480582566015569),
 np.float64(0.8480386109775206),
 np.float64(0.8479699826474321),
 np.float64(0.8479439385247209),
 np.float64(0.847923523971165),
 np.float64(0.8478470678735055),
 np.float64(0.8478369274587166),
 np.float64(0.847504687221502),
 np.float64(0.847052999628478),
 np.float64(0.846847452002664),
 np.float64(0.8468158507040768),
 np.float64(0.8465106573160525),
 np.float64(0.846492531509144),
 np.float64(0.8464847320253329),
 np.float64(0.8464237504377213),
 np.float64(0.8463063241707143),
 np.float64(0.8462291714986421),
 np.float64(0.846187753128558),
 np.float64(0.846182533972234),
 np.float64(0.8461224412782797),
 np.float64(0.8460769075779125),
 np.float64(0.8458772615038603),
 np.float64(0.845444224109089),
 np.float64(0.8453570564233784),
 np.float64(0.8451664807570339),
 np.float64(0.8451505075347755),
 np.float64(0.8450458592962645),
 np.float64(0.844929784124911),
 np.float64(0.844888982628485),
 np.float64(0.844864773548118),
 np.float64(0.8447394512461243),
 np.float64(0.8446817611034435),
 np.float64(0.844620501510062),
 np.float64(0.8445815080900819),
 np.float64(0.8443876572676129),
 np.float64(0.8442631630866687),
 np.float64(0.844092805431),
 np.float64(0.8440204335445032),
 np.float64(0.844017659911922),
 np.float64(0.8439388059947814),
 np.float64(0.8439298448436995),
 np.float64(0.8439283080413263),
 np.float64(0.8437869163242083),
 np.float64(0.8436967853444484),
 np.float64(0.8435224936217803),
 np.float64(0.8434810756903803),
 np.float64(0.8433625333553042),
 np.float64(0.8430394115661172),
 np.float64(0.8428888553703338),
 np.float64(0.8427963278480491),
 np.float64(0.8427963278480491),
 np.float64(0.8426585683512267),
 np.float64(0.8420101041818755),
 np.float64(0.842009800487247),
 np.float64(0.8419925484328515),
 np.float64(0.8416873025779112),
 np.float64(0.8416795828940935),
 np.float64(0.8416628345681219),
 np.float64(0.8415791202925574),
 np.float64(0.84137155134965),
 np.float64(0.8412231697925568),
 np.float64(0.841187212818876),
 np.float64(0.8409193696806407),
 np.float64(0.8408772620244138),
 np.float64(0.8407785176401321),
 np.float64(0.8404421481613228),
 np.float64(0.8403949154414366),
 np.float64(0.8403416785318236),
 np.float64(0.8402932804860448),
 np.float64(0.8402932804860448),
 np.float64(0.8402298342938184),
 np.float64(0.8400529367453438),
 np.float64(0.8399002677644529),
 np.float64(0.8397459811599235),
 np.float64(0.8396826314781785),
 np.float64(0.8396604515867876),
 np.float64(0.8395834088786854),
 np.float64(0.8395773477425413),
 np.float64(0.8395573813375221),
 np.float64(0.8394310103537556),
 np.float64(0.8394310103537556),
 np.float64(0.8394310103537554),
 np.float64(0.8391818108628729),
 np.float64(0.8391818108628729),
 np.float64(0.8390182128560398),
 np.float64(0.8389632715350609),
 np.float64(0.8389362481015983),
 np.float64(0.8389174482102915),
 np.float64(0.8388030351294528),
 np.float64(0.8387529675325376),
 np.float64(0.8387529675325376),
 np.float64(0.8387338375443048),
 np.float64(0.8387044525618186),
 np.float64(0.8386148622031027),
 np.float64(0.838513248097182),
 np.float64(0.8384166783737481),
 np.float64(0.8383343572297979),
 np.float64(0.8382582324348159),
 np.float64(0.8382582324348159),
 np.float64(0.8382582324348159),
 np.float64(0.8382253647186632),
 np.float64(0.8381784235382534),
 np.float64(0.8381784235382534),
 np.float64(0.8379850013902557),
 np.float64(0.8369928239123309),
 np.float64(0.836967610834211),
 np.float64(0.836967610834211),
 np.float64(0.8368762982227846),
 np.float64(0.8368362496765575),
 np.float64(0.8368094387434413),
 np.float64(0.8367747574410435),
 np.float64(0.8367362007980411),
 np.float64(0.8367362007980411),
 np.float64(0.836704823034964),
 np.float64(0.8366974172853786),
 np.float64(0.8366619632538246),
 np.float64(0.8366260026418976),
 np.float64(0.8365348333791818),
 np.float64(0.8365283838357951),
 np.float64(0.8362861698504659),
 np.float64(0.8362861698504659),
 np.float64(0.836147109958398),
 np.float64(0.8359153164026386),
 np.float64(0.8355925012731468),
 np.float64(0.8355618907699638),
 np.float64(0.8355618907699638),
 np.float64(0.8355583028637099),
 np.float64(0.8354784373327229),
 np.float64(0.8354784373327229),
 np.float64(0.835383250042913),
 np.float64(0.835285424191415),
 np.float64(0.8351447281138599),
 np.float64(0.835023006880223),
 np.float64(0.8347699920761212),
 np.float64(0.834482275253468),
 np.float64(0.8344173955865022),
 np.float64(0.8344173955865022),
 np.float64(0.8343607710069463),
 np.float64(0.8343588336366278),
 np.float64(0.8341176392137899),
 np.float64(0.8341153013397831),
 np.float64(0.8339766237461201),
 np.float64(0.833898788398534),
 np.float64(0.833898788398534),
 np.float64(0.83376695815121),
 np.float64(0.8336061633010882),
 np.float64(0.8335440300881545),
 np.float64(0.8332485752158292),
 np.float64(0.8332395798701556),
 np.float64(0.8331102314482676),
 np.float64(0.8331102314482673),
 np.float64(0.8330895082152844),
 np.float64(0.8330677290769188),
 np.float64(0.8328533429085091),
 np.float64(0.8328001075179036),
 np.float64(0.8327668810683522),
 np.float64(0.8327619250775732),
 np.float64(0.8327498164879621),
 np.float64(0.8327422104480374),
 np.float64(0.8321170637791355),
 np.float64(0.832018884429634),
 np.float64(0.8320138412357478),
 np.float64(0.8319909555358482),
 np.float64(0.8319891566700142),
 np.float64(0.8318293041094266),
 np.float64(0.8317751017813539),
 np.float64(0.8316534770379155),
 np.float64(0.8316315812035163),
 np.float64(0.8315995246276822),
 np.float64(0.8315938281662972),
 np.float64(0.831567553545896),
 np.float64(0.831146001652188),
 np.float64(0.8311389712521394),
 np.float64(0.8310996194427346),
 np.float64(0.8310710361755022),
 np.float64(0.8310119782696104),
 np.float64(0.8309930482760716),
 np.float64(0.8309513518632311),
 np.float64(0.8308641470993082),
 np.float64(0.8308641470993082),
 np.float64(0.8308411643439468),
 np.float64(0.830840210494357),
 np.float64(0.8308119919485896),
 np.float64(0.8308026365371343),
 np.float64(0.8308026365371343),
 np.float64(0.830787156128524),
 np.float64(0.8304553058432139),
 np.float64(0.8302784760975994),
 np.float64(0.8299255270193754),
 np.float64(0.8299255270193754),
 np.float64(0.82986283650915),
 np.float64(0.8297976527968063),
 np.float64(0.8297754201264147),
 np.float64(0.8297105835810717),
 np.float64(0.8297105835810717),
 np.float64(0.8296913151859066),
 np.float64(0.8296637035490865),
 np.float64(0.8295559869970252),
 np.float64(0.8295128452656994),
 np.float64(0.8292080098200744),
 np.float64(0.8292007296710542),
 np.float64(0.8291440909263988),
 np.float64(0.82911849492816),
 np.float64(0.8290966651961769),
 np.float64(0.8290966651961769),
 np.float64(0.8290038747443309),
 np.float64(0.8288514544160724),
 np.float64(0.8288048729749121),
 np.float64(0.8286552087973148),
 np.float64(0.82860195465631),
 np.float64(0.8285397292529948),
 np.float64(0.8284275269693722),
 np.float64(0.8280061252807687),
 np.float64(0.8280061252807686),
 np.float64(0.827951887783085),
 np.float64(0.8278968621522786),
 np.float64(0.8278147417471614),
 np.float64(0.8277147007137242),
 np.float64(0.8276759873990981),
 np.float64(0.8275000615395248),
 np.float64(0.8272521764482443),
 np.float64(0.8272167078360365),
 np.float64(0.8271700515448929),
 np.float64(0.8269921464648397),
 np.float64(0.8268812825271746),
 np.float64(0.8268105151810846),
 np.float64(0.8265703615900084),
 np.float64(0.8265205233313883),
 np.float64(0.8265038703914843),
 np.float64(0.8263971352105148),
 np.float64(0.8263866308459606),
 np.float64(0.8262612936210222),
 np.float64(0.8261574569737289),
 np.float64(0.8261302092552277),
 np.float64(0.8261150595170018),
 np.float64(0.8258026237284172),
 np.float64(0.8257056625802314),
 np.float64(0.825535668725752),
 np.float64(0.8254633234317111),
 np.float64(0.8254596452488123),
 np.float64(0.8254368698231808),
 np.float64(0.825223849279449),
 np.float64(0.825217234758961),
 np.float64(0.8251517342207363),
 np.float64(0.8250671933682542),
 np.float64(0.8250565470871551),
 np.float64(0.824922861596217),
 np.float64(0.8246540427445209),
 np.float64(0.8246271088340134),
 np.float64(0.8246271088340134),
 np.float64(0.8245133331400747),
 np.float64(0.8242591770326151),
 np.float64(0.8239332849470333),
 np.float64(0.8239007021289068),
 np.float64(0.8237627607764659),
 np.float64(0.8237436259365735),
 np.float64(0.823716968852586),
 np.float64(0.8236364301121848),
 np.float64(0.8236129770626404),
 np.float64(0.823357474349167),
 np.float64(0.8232792663771474),
 np.float64(0.8231532432969494),
 np.float64(0.8231018010419044),
 np.float64(0.8230032928005242),
 np.float64(0.8228872730462855),
 np.float64(0.8228534756031074),
 np.float64(0.8228329680256313),
 np.float64(0.8228165983263246),
 np.float64(0.8227974031162937),
 np.float64(0.8227974031162937),
 np.float64(0.8227917660162606),
 np.float64(0.8224388516055524),
 np.float64(0.8224321366749834),
 np.float64(0.8223196532258836),
 np.float64(0.8221559350820042),
 np.float64(0.8220303074723233),
 np.float64(0.8220059529859499),
 np.float64(0.8219800266846059),
 np.float64(0.8218083979737943),
 np.float64(0.8217911796418773),
 np.float64(0.821742598499718),
 np.float64(0.8216317159143806),
 np.float64(0.8214568059853964),
 np.float64(0.8214152514229174),
 np.float64(0.8213219768610555),
 np.float64(0.8213219768610555),
 np.float64(0.8213219768610555),
 np.float64(0.8213219768610555),
 np.float64(0.8213219768610555),
 np.float64(0.8213219768610555),
 np.float64(0.8212041219293515),
 np.float64(0.8210877053924578),
 np.float64(0.8209371639108622),
 np.float64(0.8208187318265322),
 np.float64(0.8207961811823307),
 np.float64(0.8207776523704079),
 np.float64(0.8207723071340022),
 np.float64(0.8207723071340022),
 np.float64(0.8205462432120266),
 np.float64(0.820505488344382),
 np.float64(0.820461646049496),
 np.float64(0.8202620883729264),
 np.float64(0.8200123208491065),
 np.float64(0.8200123208491064),
 np.float64(0.8197030029662247),
 np.float64(0.8195635049256065),
 np.float64(0.8193937513073861),
 np.float64(0.8193544013684679),
 np.float64(0.8193398143995357),
 np.float64(0.819293183370888),
 np.float64(0.8192240884364729),
 np.float64(0.8190499891701488),
 np.float64(0.8190499891701488),
 np.float64(0.8190168404296374),
 np.float64(0.8185723217118197),
 np.float64(0.8184363079007778),
 np.float64(0.8183589737159368),
 np.float64(0.8182949037055197),
 np.float64(0.818226680823207),
 np.float64(0.8182150611157195),
 np.float64(0.8180980066829711),
 np.float64(0.8180562701828453),
 np.float64(0.8177943991735357),
 np.float64(0.8176987693467609),
 np.float64(0.8174693870667826),
 np.float64(0.8173197236991689),
 np.float64(0.8173197236991689),
 np.float64(0.8170330599385222),
 np.float64(0.8169730850097644),
 np.float64(0.8168109806603875),
 np.float64(0.816796752468666),
 np.float64(0.8167933136278529),
 np.float64(0.816714973543337),
 np.float64(0.8165767456401969),
 np.float64(0.8165396467969716),
 np.float64(0.8165396467969716),
 np.float64(0.8165047976175983),
 np.float64(0.8164796114151777),
 np.float64(0.8164135352719485),
 np.float64(0.8163996392261397),
 np.float64(0.8163996392261397),
 np.float64(0.8163996392261397),
 np.float64(0.8163041087655418),
 np.float64(0.8158634250585287),
 np.float64(0.8158328100757997),
 np.float64(0.8158328100757997),
 np.float64(0.8158328100757997),
 np.float64(0.8157231307935819),
 np.float64(0.8156591338404969),
 np.float64(0.8156339410491085),
 np.float64(0.8156323944248773),
 np.float64(0.8155229368288722),
 np.float64(0.8153434679399308),
 np.float64(0.8153113780872987),

In [ ]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999999)),
 (1, np.float64(0.8416873025779112)),
 (2, np.float64(0.6526490763641752)),
 (3, np.float64(0.825223849279449)),
 (4, np.float64(0.867432339342686)),
 (5, np.float64(0.8315938281662972)),
 (6, np.float64(0.7713200044069981)),
 (7, np.float64(0.7045727982651319)),
 (8, np.float64(0.7360341943451943)),
 (9, np.float64(0.7081084318539143)),
 (10, np.float64(0.7537947016538906)),
 (11, np.float64(0.46185961356439786)),
 (12, np.float64(0.8331102314482673)),
 (13, np.float64(0.7471915767511771)),
 (14, np.float64(0.7226337330201483)),
 (15, np.float64(0.7576540315319455)),
 (16, np.float64(0.7342613253084151)),
 (17, np.float64(0.8365283838357951)),
 (18, np.float64(0.49270005691120633)),
 (19, np.float64(0.766076176300901)),
 (20, np.float64(0.6509897444765201)),
 (21, np.float64(0.6942506121289954)),
 (22, np.float64(0.719496188772248)),
 (23, np.float64(0.7420708969237275)),
 (24, np.float64(0.7317643566886757)),
 (25, np.float64(0.8108583424298901)),
 (26, np.float64(0.7597376631108449)),
 (27, np.float64(0.884473256271032)),
 (28, np.float64(0.8219800266846059)),
 (29, np.float64(0.7496122746318115)),
 (30, np.float64(0.7471800157866986)),
 (31, np.float64(0.8482104939606733)),
 (32, np.float64(0.5936612824260631)),
 (33, np.float64(0.7045271601194928)),
 (34, np.float64(0.7420708969237274)),
 (35, np.float64(0.8265703615900084)),
 (36, np.float64(0.6721317191389091)),
 (37, np.float64(0.76265612137098)),
 (38, np.float64(0.6224452750505048)),
 (39, np.float64(0.7514054889823876)),
 (40, np.float64(0.5787314224871988)),
 (41, np.float64(0.7716772034284137)),
 (42, np.float64(0.7505014609977897)),
 (43, np.float64(0.7912941408506223)),
 (44, np.float64(0.6945349227421149)),
 (45, np.float64(0.5461653055029808)),
 (46, np.float64(0.756915897904519)),
 (47, np.float64(0.7649366412008142)),
 (48, np.float64(0.2564206469580993)),
 (49, np.float64(0.5759184152070187)),
 (50, np.float64(0.6346369004791754)),
 (51, np.float64(0.570434436069858)),
 (52, np.float64(0.8214568059853964)),
 (53, np.float64(0.8368094387434413)),
 (54, np.float64(0.7680859582669267)),
 (55, np.float64(0.793443835016137)),
 (56, np.float64(0.6058983501441946)),
 (57, np.float64(0.15015895230183152)),
 (58, np.float64(0.13900261464929298)),
 (59, np.float64(0.7067702680764791)),
 (60, np.float64(0.6856954513630552)),
 (61, np.float64(0.6718394226943054)),
 (62, np.float64(0.6824706896413943)),
 (63, np.float64(0.7924924416944147)),
 (64, np.float64(0.7605464185151383)),
 (65, np.float64(0.7990105759888348)),
 (66, np.float64(0.6256320404563431)),
 (67, np.float64(0.4504768569054945)),
 (68, np.float64(0.7848837693328969)),
 (69, np.float64(0.7174537975663918)),
 (70, np.float64(0.5180414878950118)),
 (71, np.float64(0.03296042641891439)),
 (72, np.float64(0.7114901508156796)),
 (73, np.float64(0.8209371639108622)),
 (74, np.float64(0.7668541428181308)),
 (75, np.float64(0.6316114558673486)),
 (76, np.float64(0.8262612936210222)),
 (77, np.float64(0.6510532876927337)),
 (78, np.float64(0.8121271103613458)),
 (79, np.float64(0.5823091586062912)),
 (80, np.float64(0.6778422055851223)),
 (81, np.float64(0.632287553615257)),
 (82, np.float64(0.8280061252807687)),
 (83, np.float64(0.06262039963566078)),
 (84, np.float64(0.6632037776979233)),
 (85, np.float64(0.6798158356959114)),
 (86, np.float64(0.3029491750720973)),
 (87, np.float64(0.6811821459908973)),
 (88, np.float64(0.811251600578336)),
 (89, np.float64(0.7754495141323867)),
 (90, np.float64(0.7980154036730901)),
 (91, np.float64(0.35199513294045237)),
 (92, np.float64(0.8478369274587166)),
 (93, np.float64(0.8050350216073415)),
 (94, np.float64(0.7985787399403966)),
 (95, np.float64(0.9027428883008348)),
 (96, np.float64(0.698310557229165)),
 (97, np.float64(0.593989785789484)),
 (98, np.float64(0.8787951670201131)),
 (99, np.float64(0.7046855342161588)),
 (100, np.float64(0.6996311511146016)),
 (101, np.float64(0.7824886169543916)),
 (102, np.float64(0.5722373306917392)),
 (103, np.float64(0.8437869163242083)),
 (104, np.float64(0.8365348333791818)),
 (105, np.float64(0.7347546209251673)),
 (106, np.float64(0.8695231068074601)),
 (107, np.float64(0.7946381037580956)),
 (108, np.float64(0.7740378205554276)),
 (109, np.float64(0.7728752155285064)),
 (110, np.float64(0.7712010380881728)),
 (111, np.float64(0.7437254606208829)),
 (112, np.float64(0.7640421172391171)),
 (113, np.float64(0.7906303281208061)),
 (114, np.float64(0.7935970564733994)),
 (115, np.float64(0.7688138357853773)),
 (116, np.float64(0.7146787038102788)),
 (117, np.float64(0.7470069734882455)),
 (118, np.float64(0.7986748503773476)),
 (119, np.float64(0.8578981306451199)),
 (120, np.float64(0.8416628345681219)),
 (121, np.float64(0.6004894459827869)),
 (122, np.float64(0.724572771399986)),
 (123, np.float64(0.8924264398244509)),
 (124, np.float64(0.8073622643089048)),
 (125, np.float64(0.8271700515448929)),
 (126, np.float64(0.7466944363405623)),
 (127, np.float64(0.7259590210527437)),
 (128, np.float64(0.8297976527968063)),
 (129, np.float64(0.823716968852586)),
 (130, np.float64(0.653176987396406)),
 (131, np.float64(0.3030177699275155)),
 (132, np.float64(0.7616953842465735)),
 (133, np.float64(0.8339766237461201)),
 (134, np.float64(0.7672091600290804)),
 (135, np.float64(0.541093362340218)),
 (136, np.float64(0.7540460217756926)),
 (137, np.float64(0.4481225782900364)),
 (138, np.float64(0.8546098958286888)),
 (139, np.float64(0.8875254321815702)),
 (140, np.float64(0.4078578089871719)),
 (141, np.float64(0.7395936525063223)),
 (142, np.float64(0.6729435145199987)),
 (143, np.float64(0.5936612824260631)),
 (144, np.float64(0.8556059286654353)),
 (145, np.float64(0.830787156128524)),
 (146, np.float64(0.19487736480813905)),
 (147, np.float64(0.49355308353966404)),
 (148, np.float64(0.5176920887835139)),
 (149, np.float64(0.8383343572297979)),
 (150, np.float64(0.7711915012777137)),
 (151, np.float64(0.8681455162539514)),
 (152, np.float64(0.7884503279814605)),
 (153, np.float64(0.5836078408098064)),
 (154, np.float64(0.7324524981783167)),
 (155, np.float64(0.7862419667826621)),
 (156, np.float64(0.8854420040004312)),
 (157, np.float64(0.6546930320359853)),
 (158, np.float64(0.8757527339796719)),
 (159, np.float64(0.8014403624871377)),
 (160, np.float64(0.6703746625150313)),
 (161, np.float64(0.8491463612433312)),
 (162, np.float64(0.4401075950086664)),
 (163, np.float64(0.8202620883729264)),
 (164, np.float64(0.41228264262110453)),
 (165, np.float64(0.885649523387772)),
 (166, np.float64(0.8180562701828453)),
 (167, np.float64(0.32348996080459286)),
 (168, np.float64(0.6396365006348027)),
 (169, np.float64(0.7686658934439423)),
 (170, np.float64(0.5659869491878572)),
 (171, np.float64(0.5247233633359513)),
 (172, np.float64(0.8702921193985093)),
 (173, np.float64(0.4546941724878387)),
 (174, np.float64(0.8223196532258836)),
 (175, np.float64(0.6901119163831314)),
 (176, np.float64(0.8420101041818755)),
 (177, np.float64(0.809207565977979)),
 (178, np.float64(0.7712835856975168)),
 (179, np.float64(0.4681675333547931)),
 (180, np.float64(0.8681916286895672)),
 (181, np.float64(0.8579664175191296)),
 (182, np.float64(0.6071798082614284)),
 (183, np.float64(0.8631471815536194)),
 (184, np.float64(0.7258838076881202)),
 (185, np.float64(0.6899770548425322)),
 (186, np.float64(0.8514084099476587)),
 (187, np.float64(0.3030177699275155)),
 (188, np.float64(0.827951887783085)),
 (189, np.float64(0.6084176888700878)),
 (190, np.float64(0.705953980339406)),
 (191, np.float64(0.8286552087973148)),
 (192, np.float64(0.7518318175067062)),
 (193, np.float64(0.11057590284882254)),
 (194, np.float64(0.8122410358499959)),
 (195, np.float64(0.5604588569096064)),
 (196, np.float64(0.8436967853444484)),
 (197, np.float64(0.7037881150466205)),
 (198, np.float64(0.6581462121525917)),
 (199, np.float64(0.8535892063295424)),
 (200, np.float64(0.8379850013902557)),
 (201, np.float64(0.8852772466539196)),
 (202, np.float64(0.6685414379677108)),
 (203, np.float64(0.5708377246301546)),
 (204, np.float64(0.8148316822377485)),
 (205, np.float64(0.43856893581644646)),
 (206, np.float64(0.7767799255373664)),
 (207, np.float64(0.8276759873990981)),
 (208, np.float64(0.816714973543337)),
 (209, np.float64(0.872374265406781)),
 (210, np.float64(0.6901119163831314)),
 (211, np.float64(0.5757093056299422)),
 (212, np.float64(0.8698045155674722)),
 (213, np.float64(0.8261574569737289)),
 (214, np.float64(0.7352011050070909)),
 (215, np.float64(0.88281120183691)),
 (216, np.float64(0.7891244021238495)),
 (217, np.float64(0.6711437158585134)),
 (218, np.float64(0.47994301015111585)),
 (219, np.float64(0.4185293493274849)),
 (220, np.float64(0.8254596452488123)),
 (221, np.float64(0.5264042507850525)),
 (222, np.float64(0.33569873908454345)),
 (223, np.float64(0.5705542797191165)),
 (224, np.float64(0.6057043198608881)),
 (225, np.float64(0.5531236094335877)),
 (226, np.float64(0.4911258381618033)),
 (227, np.float64(0.8039258546938164)),
 (228, np.float64(0.6196560166755904)),
 (229, np.float64(0.7246631862556304)),
 (230, np.float64(0.8389362481015983)),
 (231, np.float64(0.7470481670117431)),
 (232, np.float64(0.7613956598644497)),
 (233, np.float64(0.7937758771845063)),
 (234, np.float64(0.7147671160558884)),
 (235, np.float64(0.7801907366062724)),
 (236, np.float64(0.6984250381483095)),
 (237, np.float64(0.5894712910106256)),
 (238, np.float64(0.7907812009173624)),
 (239, np.float64(0.5210975450694593)),
 (240, np.float64(0.8731018096068464)),
 (241, np.float64(0.6346369004791754)),
 (242, np.float64(0.7680517841655574)),
 (243, np.float64(0.7843517658046371)),
 (244, np.float64(0.727085884854669)),
 (245, np.float64(0.8227974031162937)),
 (246, np.float64(0.7822264953434088)),
 (247, np.float64(0.6775560626053252)),
 (248, np.float64(0.793703870429087)),
 (249, np.float64(0.7695942662260618)),
 (250, np.float64(0.7640434005918376)),
 (251, np.float64(0.6674067050673691)),
 (252, np.float64(0.7755779537026999)),
 (253, np.float64(0.6541214700412838)),
 (254, np.float64(0.7734744790457181)),
 (255, np.float64(0.385748829534351)),
 (256, np.float64(0.6975039521313406)),
 (257, np.float64(0.6130517101256041)),
 (258, np.float64(0.3260286127549389)),
 (259, np.float64(0.6378429543211206)),
 (260, np.float64(0.8133618765628732)),
 (261, np.float64(0.8701552574593399)),
 (262, np.float64(0.8335440300881545)),
 (263, np.float64(0.736761042285248)),
 (264, np.float64(0.4614459698648014)),
 (265, np.float64(0.6095563085696465)),
 (266, np.float64(0.8039855701498738)),
 (267, np.float64(0.7923413043174613)),
 (268, np.float64(0.7283288432769918)),
 (269, np.float64(0.7931786976016003)),
 (270, np.float64(0.8347699920761212)),
 (271, np.float64(0.7449860131535968)),
 (272, np.float64(0.514331772712468)),
 (273, np.float64(0.8040545569801687)),
 (274, np.float64(0.7567148722361813)),
 (275, np.float64(0.7605072637614926)),
 (276, np.float64(0.8004746249223542)),
 (277, np.float64(0.6635836026292156)),
 (278, np.float64(0.8147657938051934)),
 (279, np.float64(0.7943094740724319)),
 (280, np.float64(0.597599517042218)),
 (281, np.float64(0.8207776523704079)),
 (282, np.float64(0.7980669138002476)),
 (283, np.float64(0.6179706390756794)),
 (284, np.float64(0.5681480304572288)),
 (285, np.float64(0.6547715764829192)),
 (286, np.float64(0.8565830663280116)),
 (287, np.float64(0.8628545897404774)),
 (288, np.float64(0.8585885619373651)),
 (289, np.float64(0.6328233440338147)),
 (290, np.float64(0.7862807013359245)),
 (291, np.float64(0.5503576680476433)),
 (292, np.float64(0.6094427030842798)),
 (293, np.float64(0.7431008362076216)),
 (294, np.float64(0.31112268180856767)),
 (295, np.float64(0.5347189922259671)),
 (296, np.float64(0.8640967030502926)),
 (297, np.float64(0.8081253785429663)),
 (298, np.float64(0.7811297132049935)),
 (299, np.float64(0.8354784373327229)),
 (300, np.float64(0.8524196065233043)),
 (301, np.float64(0.6111956611225047)),
 (302, np.float64(0.14992096095312893)),
 (303, np.float64(0.7783841644730535)),
 (304, np.float64(0.4321265360270032)),
 (305, np.float64(0.844092805431)),
 (306, np.float64(0.5306417101978104)),
 (307, np.float64(0.5690318266862788)),
 (308, np.float64(0.5489806678336755)),
 (309, np.float64(0.44388511701634414)),
 (310, np.float64(0.7950844033926537)),
 (311, np.float64(0.6583061632566529)),
 (312, np.float64(0.39617243019734927)),
 (313, np.float64(0.5565531726927956)),
 (314, np.float64(0.6121772572252764)),
 (315, np.float64(0.40813899330805015)),
 (316, np.float64(0.7500551531419651)),
 (317, np.float64(0.3401158277567084)),
 (318, np.float64(0.6142874918776117)),
 (319, np.float64(0.46912832414738176)),
 (320, np.float64(0.7209137030985489)),
 (321, np.float64(0.7625783112272922)),
 (322, np.float64(0.8979802266666134)),
 (323, np.float64(0.00718866579565762)),
 (324, np.float64(0.3612879729006369)),
 (325, np.float64(0.7806843262826129)),
 (326, np.float64(0.7698409618104093)),
 (327, np.float64(0.8034481225010088)),
 (328, np.float64(0.7437559287362504)),
 (329, np.float64(0.844888982628485)),
 (330, np.float64(0.8464237504377213)),
 (331, np.float64(0.5977866163332949)),
 (332, np.float64(0.7650664223586027)),
 (333, np.float64(0.818226680823207)),
 (334, np.float64(0.7789523079072121)),
 (335, np.float64(0.7132510944517954)),
 (336, np.float64(0.703352388301788)),
 (337, np.float64(0.6295493216103061)),
 (338, np.float64(0.6091257055468821)),
 (339, np.float64(0.6984165210855312)),
 (340, np.float64(0.6106881349584287)),
 (341, np.float64(0.632577186101775)),
 (342, np.float64(0.7644162405699426)),
 (343, np.float64(0.7459944172481215)),
 (344, np.float64(0.14843871673787418)),
 (345, np.float64(0.1285516996001614)),
 (346, np.float64(0.6095563085696465)),
 (347, np.float64(0.3773529806851713)),
 (348, np.float64(0.736761042285248)),
 (349, np.float64(0.8265205233313883)),
 (350, np.float64(0.4546941724878387)),
 (351, np.float64(0.7366856509680473)),
 (352, np.float64(0.7078196437375586)),
 (353, np.float64(0.7230050539571841)),
 (354, np.float64(0.8149275481633396)),
 (355, np.float64(0.8447394512461243)),
 (356, np.float64(0.7931642012483637)),
 (357, np.float64(0.41066098843052773)),
 (358, np.float64(0.5769464556557234)),
 (359, np.float64(0.5983832051166799)),
 (360, np.float64(0.8341153013397831)),
 (361, np.float64(0.7984946861368537)),
 (362, np.float64(0.582319523280425)),
 (363, np.float64(0.8389174482102915)),
 (364, np.float64(0.6008718748250954)),
 (365, np.float64(0.8460769075779125)),
 (366, np.float64(0.5540638221654688)),
 (367, np.float64(0.7942711932522469)),
 (368, np.float64(0.7994708721739862)),
 (369, np.float64(0.7768831925383726)),
 (370, np.float64(0.7702062113545365)),
 (371, np.float64(0.5604559738833801)),
 (372, np.float64(0.4566701797041237)),
 (373, np.float64(0.8439298448436995)),
 (374, np.float64(0.7007546562294541)),
 (375, np.float64(0.49877004913620815)),
 (376, np.float64(0.5063062456392479)),
 (377, np.float64(0.41858443877323537)),
 (378, np.float64(0.6585225946375595)),
 (379, np.float64(0.47625741987041986)),
 (380, np.float64(0.8156339410491085)),
 (381, np.float64(0.02006329924645778)),
 (382, np.float64(0.5667660093627923)),
 (383, np.float64(0.807044365549861)),
 (384, np.float64(0.6622360282432558)),
 (385, np.float64(0.8220059529859499)),
 (386, np.float64(0.8387338375443048)),
 (387, np.float64(0.825535668725752)),
 (388, np.float64(0.749760956169227)),
 (389, np.float64(0.6326487897038043)),
 (390, np.float64(0.8343607710069463)),
 (391, np.float64(0.6650133041020698)),
 (392, np.float64(0.6170358068857944)),
 (393, np.float64(0.7193230782783598)),
 (394, np.float64(0.8440204335445032)),
 (395, np.float64(0.7471137603845457)),
 (396, np.float64(0.8579664175191296)),
 (397, np.float64(0.3681253215822804)),
 (398, np.float64(0.5994011476508345)),
 (399, np.float64(0.722666309764043)),
 (400, np.float64(0.6690222882533378)),
 (401, np.float64(0.49147290666969035)),
 (402, np.float64(0.6462816160396913)),
 (403, np.float64(0.6564363922112098)),
 (404, np.float64(0.6213137835915125)),
 (405, np.float64(0.6865175834853027)),
 (406, np.float64(0.4655563411397783)),
 (407, np.float64(0.7107173347761524)),
 (408, np.float64(0.7317045814372815)),
 (409, np.float64(0.8104578196381382)),
 (410, np.float64(0.8133975016129154)),
 (411, np.float64(0.7252671132012547)),
 (412, np.float64(0.37394677681389477)),
 (413, np.float64(0.5972092662039584)),
 (414, np.float64(0.5154261035738588)),
 (415, np.float64(0.8643439424395689)),
 (416, np.float64(0.8327422104480374)),
 (417, np.float64(0.7955787097292937)),
 (418, np.float64(0.5934784235722926)),
 (419, np.float64(0.7548842180980467)),
 (420, np.float64(0.8193937513073861)),
 (421, np.float64(0.7899315036130858)),
 (422, np.float64(0.74607370574763)),
 (423, np.float64(0.7512986935790769)),
 (424, np.float64(0.7429014461141575)),
 (425, np.float64(0.8291440909263988)),
 (426, np.float64(0.787085045003927)),
 (427, np.float64(0.583962213524545)),
 (428, np.float64(0.8071658215879804)),
 (429, np.float64(0.831567553545896)),
 (430, np.float64(0.7366308754523931)),
 (431, np.float64(0.8355618907699638)),
 (432, np.float64(0.7940726620989315)),
 (433, np.float64(0.689873614535792)),
 (434, np.float64(0.6047566525966571)),
 (435, np.float64(0.5540664129618231)),
 (436, np.float64(0.006246706706380372)),
 (437, np.float64(0.7014139043480837)),
 (438, np.float64(0.36359911408132045)),
 (439, np.float64(0.703405960676445)),
 (440, np.float64(0.4328746898721744)),
 (441, np.float64(0.4911258381618033)),
 (442, np.float64(0.849372622088587)),
 (443, np.float64(0.6125649333788633)),
 (444, np.float64(0.7227765061501316)),
 (445, np.float64(0.6583402541675992)),
 (446, np.float64(0.8533112958772527)),
 (447, np.float64(0.6809709576069719)),
 (448, np.float64(0.49029684261031997)),
 (449, np.float64(0.5708377246301547)),
 (450, np.float64(0.5962765492453991)),
 (451, np.float64(0.8720387103975634)),
 (452, np.float64(0.7667926719546856)),
 (453, np.float64(0.6315623345540706)),
 (454, np.float64(0.8893776057664129)),
 (455, np.float64(0.8736031296758948)),
 (456, np.float64(0.5610703218625441)),
 (457, np.float64(0.29687743347574835)),
 (458, np.float64(0.5152681138711741)),
 (459, np.float64(0.8069425625681356)),
 (460, np.float64(0.6854436938990578)),
 (461, np.float64(0.49596278082988)),
 (462, np.float64(0.5619547177555423)),
 (463, np.float64(0.6143543482770489)),
 (464, np.float64(0.8308641470993082)),
 (465, np.float64(0.3050182414281228)),
 (466, np.float64(0.3899536957477816)),
 (467, np.float64(0.26985658288804953)),
 (468, np.float64(0.7314891712973325)),
 (469, np.float64(0.6412566193797834)),
 (470, np.float64(0.6730047998454313)),
 (471, np.float64(0.41019512215641685)),
 (472, np.float64(0.39384074150633)),
 (473, np.float64(0.7715685785576661)),
 (474, np.float64(0.6701508559693272)),
 (475, np.float64(0.7086491680066592)),
 (476, np.float64(0.3501466836063974)),
 (477, np.float64(0.5927380805401075)),
 (478, np.float64(0.8197030029662247)),
 (479, np.float64(0.21311034188766914)),
 (480, np.float64(0.7674359484611335)),
 (481, np.float64(0.5988301400008484)),
 (482, np.float64(0.7705595047021396)),
 (483, np.float64(0.7439948589210567)),
 (484, np.float64(0.5894712910106257)),
 (485, np.float64(0.7433253307975866)),
 (486, np.float64(0.32756107257971107)),
 (487, np.float64(0.6214514659922326)),
 (488, np.float64(0.4704528241660792)),
 (489, np.float64(0.6248007968076891)),
 (490, np.float64(0.5931769832885401)),
 (491, np.float64(0.7984079133067344)),
 (492, np.float64(0.16409746983071938)),
 (493, np.float64(0.7235455510442631)),
 (494, np.float64(0.7781267237509735)),
 (495, np.float64(0.6036569397138588)),
 (496, np.float64(0.2947277563077593)),
 (497, np.float64(0.3681253215822804)),
 (498, np.float64(0.4401075950086664)),
 (499, np.float64(0.14003423477548477)),
 (500, np.float64(0.575852693093622)),
 (501, np.float64(0.8013836814734224)),
 (502, np.float64(0.7962438236041488)),

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])[1:6]

[(2219, np.float64(0.9034437204570136)),
 (95, np.float64(0.9027428883008348)),
 (2444, np.float64(0.9019365452526242)),
 (2430, np.float64(0.9003123430002361)),
 (1069, np.float64(0.8981570169693702))]

In [ ]:
df.iloc[0]

movie_id                                                19995
title                                                  Avatar
tags        in the 22nd century, a parapleg marin is dispa...
Name: 0, dtype: object

In [ ]:
df.iloc[1216]

movie_id                                                10641
title                                      Autumn in New York
tags        autumn in new york follow the sexual exploit o...
Name: 1216, dtype: object

In [ ]:
df.iloc[2409]

movie_id                                                 9675
title                                                Sideways
tags        two middle-ag men embark on a spiritu journey ...
Name: 2409, dtype: object

In [ ]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distance = similarity[movie_index]

    for i in movie_list:
           print(df.iloc[i[0]].title)

In [ ]:
def recommend(movie):
    movie_index = df[df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])
    for i in movie_list[1:6]:
        print(df.iloc[i[0]].title)

In [ ]:
recommend('Iron Man')

Iron Man 3
The Incredible Hulk
Fantastic 4: Rise of the Silver Surfer
Southland Tales
Hulk

In [ ]:
recommend('Captain America: Civil War')

Iron Man 3
Captain America: The First Avenger
Thor
Iron Man
Fantastic 4: Rise of the Silver Surfer

In [ ]:
recommend('Superman')

Southland Tales
Everyone Says I Love You
The Matrix Revolutions
Batman Begins
Brooklyn's Finest

In [ ]:
similarity[0]

array([1.        , 0.8416873 , 0.65264908, ..., 0.55533223, 0.01855177,
       0.39379375])

In [ ]:
df[df['title']== 'Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [ ]:
df[df['title']== 'Avatar'].index[0]

np.int64(0)

In [ ]:
df.iloc[1216]

movie_id                                                10641
title                                      Autumn in New York
tags        autumn in new york follow the sexual exploit o...
Name: 1216, dtype: object

In [ ]:
df.iloc[1216].title

'Autumn in New York'

In [ ]:
import pickle

In [ ]:
df

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4805,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4807,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4808,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [ ]:
df.to_dict()

{'movie_id': {0: 19995,
  1: 285,
  2: 206647,
  3: 49026,
  4: 49529,
  5: 559,
  6: 38757,
  7: 99861,
  8: 767,
  9: 209112,
  10: 1452,
  11: 10764,
  12: 58,
  13: 57201,
  14: 49521,
  15: 2454,
  16: 24428,
  17: 1865,
  18: 41154,
  19: 122917,
  20: 1930,
  21: 20662,
  22: 57158,
  23: 2268,
  24: 254,
  25: 597,
  26: 271110,
  27: 44833,
  28: 135397,
  29: 37724,
  30: 558,
  31: 68721,
  32: 12155,
  33: 36668,
  34: 62211,
  35: 8373,
  36: 91314,
  37: 68728,
  38: 102382,
  39: 20526,
  40: 49013,
  41: 44912,
  42: 10193,
  43: 534,
  44: 168259,
  45: 72190,
  46: 127585,
  47: 54138,
  48: 81005,
  49: 64682,
  50: 9543,
  51: 68726,
  52: 38356,
  53: 217,
  54: 105864,
  55: 62177,
  56: 188927,
  57: 10681,
  58: 5174,
  59: 14161,
  60: 17979,
  61: 76757,
  62: 258489,
  63: 411,
  64: 246655,
  65: 155,
  66: 14160,
  67: 15512,
  68: 1726,
  69: 44826,
  70: 8487,
  71: 1735,
  72: 297761,
  73: 2698,
  74: 137113,
  75: 9804,
  76: 14869,
  77: 150540,
  78: 278927,
  79: 10138,
  80: 58595,
  81: 102651,
  82: 119450,
  83: 79698,
  84: 64686,
  85: 100402,
  86: 10192,
  87: 158852,
  88: 177572,
  89: 82690,
  90: 5255,
  91: 47933,
  92: 10191,
  93: 296,
  94: 118340,
  95: 157336,
  96: 27205,
  97: 315011,
  98: 49051,
  99: 9799,
  100: 4922,
  101: 49538,
  102: 131634,
  103: 27022,
  104: 503,
  105: 241259,
  106: 810,
  107: 68735,
  108: 87101,
  109: 10140,
  110: 676,
  111: 1858,
  112: 1966,
  113: 675,
  114: 674,
  115: 8960,
  116: 6479,
  117: 118,
  118: 2062,
  119: 272,
  120: 10527,
  121: 18360,
  122: 2080,
  123: 605,
  124: 109445,
  125: 604,
  126: 76338,
  127: 76341,
  128: 13448,
  129: 10195,
  130: 13053,
  131: 19585,
  132: 57165,
  133: 62213,
  134: 177677,
  135: 7978,
  136: 5559,
  137: 49444,
  138: 10196,
  139: 956,
  140: 117251,
  141: 50321,
  142: 11619,
  143: 266647,
  144: 82703,
  145: 652,
  146: 80321,
  147: 36669,
  148: 43074,
  149: 95,
  150: 608,
  151: 2310,
  152: 140300,
  153: 56292,
  154: 81188,
  155: 7552,
  156: 616,
  157: 147441,
  158: 13475,
  159: 557,
  160: 82702,
  161: 205584,
  162: 10048,
  163: 13183,
  164: 944,
  165: 1927,
  166: 72559,
  167: 7364,
  168: 2114,
  169: 1771,
  170: 36643,
  171: 8619,
  172: 50620,
  173: 65759,
  174: 1724,
  175: 267935,
  176: 281957,
  177: 77950,
  178: 44896,
  179: 270946,
  180: 2503,
  181: 9502,
  182: 102899,
  183: 101299,
  184: 228161,
  185: 74,
  186: 8961,
  187: 417859,
  188: 27576,
  189: 86834,
  190: 17578,
  191: 673,
  192: 6972,
  193: 82700,
  194: 10567,
  195: 181533,
  196: 38055,
  197: 671,
  198: 49524,
  199: 22,
  200: 131631,
  201: 591,
  202: 172385,
  203: 36658,
  204: 51497,
  205: 58574,
  206: 18823,
  207: 861,
  208: 1911,
  209: 49040,
  210: 415,
  211: 8871,
  212: 435,
  213: 955,
  214: 2133,
  215: 1979,
  216: 87827,
  217: 1250,
  218: 324668,
  219: 9471,
  220: 70981,
  221: 10996,
  222: 68724,
  223: 2789,
  224: 97020,
  225: 7459,
  226: 42888,
  227: 37834,
  228: 75612,
  229: 1895,
  230: 1894,
  231: 585,
  232: 76170,
  233: 1893,
  234: 49519,
  235: 2395,
  236: 12100,
  237: 290595,
  238: 98566,
  239: 49047,
  240: 9619,
  241: 308531,
  242: 166424,
  243: 1593,
  244: 254128,
  245: 714,
  246: 2024,
  247: 163,
  248: 787,
  249: 262500,
  250: 2567,
  251: 38745,
  252: 40805,
  253: 53182,
  254: 41513,
  255: 13700,
  256: 262504,
  257: 39254,
  258: 77931,
  259: 1639,
  260: 80274,
  261: 1571,
  262: 120,
  263: 10204,
  264: 8489,
  265: 10588,
  266: 2048,
  267: 1495,
  268: 10137,
  269: 10198,
  270: 286217,
  271: 1635,
  272: 24113,
  273: 9679,
  274: 98,
  275: 180,
  276: 672,
  277: 36557,
  278: 869,
  279: 280,
  280: 11322,
  281: 4982,
  282: 36955,
  283: 18487,
  284: 39451,
  285: 27581,
  286: 9268,
  287: 68718,
  288: 10545,
  289: 11688,
  290: 76163,
  291: 2059,
  292: 2486,
  293: 16523,
  294: 116711,
  295: 37710,
  296: 9946,
  297: 1372,
  298: 106646,
  299: 414,
  300: 563,
  301: 83542,
  302: 41216,
  303: 314,
  304: 184315,
  305: 9016,
  306: 18162,
  307: 138103,
  308: 257088,
  309: 10214,
  310: 205775,
  311: 11692,
  312: 22972,
  313: 227973,
  314: 29193,
  315: 1734,
  316: 3131,
  317: 76758,
  318: 9408,
  319: 9890,
  320: 855,
  321: 77953,
  322: 18,
  323: 37786,
  324: 10501,
  325: 57800,
  326: 150689,
  327: 7980,
  328: 12,
  329: 122,
  330: 121,
  331: 68737,
  332: 1995,
  333: 157353,
  334: 331,
  335: 61791,
  336: 8204,
  337: 47964,
  338: 10733,
  339: 9806,
  340: 1408,
  341: 32657,
  342: 607,
  343: 863,
  344: 44048,
  345: 5175,
  346: 2655,
  347: 22794,
  348: 8355,
  349: 116745,
  350: 4327,
  351: 1422,
  352: 10674,
  353: 7446,
  354: 65754,
  355: 1572,
  356: 10528,
  357: 271969,
  358: 10865,
  359: 258509,
  360: 2253,
  361: 10661,
  362: 257344,
  363: 644,
  364: 10756,
  365: 686,
  366: 9383,
  367: 179,
  368: 76285,
  369: 1996,
  370: 291805,
  371: 10003,
  372: 1535,
  373: 2067,
  374: 46195,
  375: 2277,
  376: 10357,
  377: 4477,
  378: 8665,
  379: 9387,
  380: 921,
  381: 49852,
  382: 4464,
  383: 664,
  384: 8358,
  385: 9836,
  386: 2502,
  387: 9772,
  388: 161,
  389: 52451,
  390: 76492,
  391: 4523,
  392: 59961,
  393: 10481,
  394: 59108,
  395: 1581,
  396: 9798,
  397: 22897,
  398: 298,
  399: 7484,
  400: 157350,
  401: 853,
  402: 10159,
  403: 9593,
  404: 1904,
  405: 9615,
  406: 51052,
  407: 297,
  408: 9884,
  409: 16858,
  410: 62764,
  411: 22538,
  412: 9341,
  413: 12107,
  414: 9637,
  415: 49049,
  416: 9339,
  417: 16281,
  418: 39691,
  419: 8247,
  420: 11253,
  421: 1949,
  422: 8452,
  423: 310,
  424: 27578,
  425: 954,
  426: 70160,
  427: 45243,
  428: 364,
  429: 7518,
  430: 11544,
  431: 9986,
  432: 8656,
  433: 146216,
  434: 9291,
  435: 55301,
  436: 109418,
  437: 11665,
  438: 6964,
  439: 11324,
  440: 12193,
  441: 9928,
  442: 754,
  443: 10202,
  444: 4147,
  445: 50546,
  446: 1701,
  447: 13027,
  448: 2289,
  449: 20504,
  450: 9574,
  451: 11618,
  452: 2300,
  453: 12096,
  454: 10200,
  455: 8834,
  456: 228150,
  457: 6068,
  458: 41515,
  459: 9023,
  460: 38317,
  461: 2157,
  462: 14462,
  463: 161795,
  464: 159824,
  465: 49948,
  466: 2135,
  467: 9822,
  468: 9705,
  469: 1656,
  470: 12159,
  471: 9678,
  472: 4442,
  473: 75,
  474: 330770,
  475: 9433,
  476: 19959,
  477: 11973,
  478: 11228,
  479: 77951,
  480: 5491,
  481: 10715,
  482: 10197,
  483: 9562,
  484: 9922,
  485: 9447,
  486: 274854,
  487: 8870,
  488: 9992,
  489: 36970,
  490: 10077,
  491: 76649,
  492: 293644,
  493: 453,
  494: 8587,
  495: 72545,
  496: 109451,
  497: 9533,
  498: 2023,
  499: 71880,
  500: 584,
  501: 309809,
  502: 4858,
  503: 17711,
  504: 328111,
  505: 8698,
  506: 93456,
  507: 602,
  508: 330,
  509: 953,
  510: 9693,
  511: 36657,
  512: 8909,
  513: 9802,
  514: 950,
  515: 1824,
  516: 2976,
  517: 11026,
  518: 332,
  519: 75656,
  520: 38365,
  521: 594,
  522: 15189,
  523: 11678,
  524: 6538,
  525: 10555,
  526: 1125,
  527: 4551,
  528: 612,
  529: 9567,
  530: 37821,
  531: 203801,
  532: 2539,
  533: 9297,
  534: 3172,
  535: 6520,
  536: 1439,
  537: 37958,
  538: 2026,
  539: 7450,
  540: 11375,
  541: 9425,
  542: 25769,
  543: 23685,
  544: 11866,
  545: 9741,
  546: 211672,
  547: 23629,
  548: 8688,
  549: 10153,
  550: 153518,
  551: 8676,
  552: 20829,
  553: 4349,
  554: 9718,
  555: 10808,
  556: 197,
  557: 25,
  558: 35,
  559: 11086,
  560: 10477,
  561: 1997,
  562: 6947,
  563: 3050,
  564: 2675,
  565: 809,
  566: 920,
  567: 4806,
  568: 7451,
  569: 228165,
  570: 3595,
  571: 16869,
  572: 879,
  573: 1573,
  574: 9257,
  575: 1903,
  576: 9697,
  577: 395,
  578: 23398,
  579: 10590,
  580: 117263,
  581: 200,
  582: 44943,
  583: 587,
  584: 10395,
  585: 57212,
  586: 152760,
  587: 2756,
  588: 33909,
  589: 49017,
  590: 9882,
  591: 2270,
  592: 978,
  593: 44564,
  594: 3132,
  595: 8814,
  596: 8427,
  597: 52520,
  598: 80585,
  599: 10592,
  600: 49021,
  601: 11535,
  602: 10550,
  603: 11258,
  604: 12610,
  605: 59981,
  606: 201088,
  607: 5137,
  608: 3093,
  609: 107846,
  610: 188207,
  611: 4614,
  612: 24021,
  613: 11371,
  614: 20352,
  615: 11517,
  616: 214756,
  617: 26428,
  618: 9824,
  619: 48988,
  620: 9008,
  621: 300673,
  622: 12113,
  623: 38778,
  624: 72331,
  625: 1844,
  626: 846,
  627: 9703,
  628: 857,
  629: 136797,
  630: 3981,
  631: 425,
  632: 6171,
  633: 72976,
  634: 603,
  635: 568,
  636: 9021,
  637: 82695,
  638: 9489,
  639: 12133,
  640: 9342,
  641: 41733,
  642: 227306,
  643: 5551,
  644: 9350,
  645: 9208,
  646: 4244,
  647: 1852,
  648: 11820,
  649: 76493,
  650: 345,
  651: 196867,
  652: 256591,
  653: 59962,
  654: 36648,
  655: 1880,
  656: 9440,
  657: 71679,
  658: 10483,
  659: 11412,
  660: 11983,
  661: 6795,
  662: 550,
  663: 11170,
  664: 9292,
  665: 10783,
  666: 100241,
  667: 257,
  668: 9947,
  669: 189,
  670: 12618,
  671: 253412,
  672: 1427,
  673: 818,
  674: 16577,
  675: 329,
  676: 12160,
  677: 9331,
  678: 300168,
  679: 9072,
  680: 3536,
  681: 9087,
  682: 12177,
  683: 12138,
  684: 273248,
  685: 9955,
  686: 50359,
  687: 1271,
  688: 693,
  689: 14306,
  690: 497,
  691: 11199,
  692: 9982,
  693: 210577,
  694: 2501,
  695: 710,
  696: 2275,
  697: 37165,
  698: 9837,
  699: 10708,
  700: 136400,
  701: 10992,
  702: 9654,
  703: 2642,
  704: 8916,
  705: 19899,
  706: 2119,
  707: 9641,
  708: 294254,
  709: 38167,
  710: 5994,
  711: 39514,
  712: 9563,
  713: 547,
  714: 1538,
  715: 9334,
  716: 11128,
  717: 75780,
  718: 8914,
  719: 13576,
  720: 39538,
  721: 10628,
  722: 14836,
  723: 8645,
  724: 9509,
  725: 10067,
  726: 9384,
  727: 9279,
  728: 1487,
  729: 9422,
  730: 77174,
  731: 4824,
  732: 9620,
  733: 9302,
  734: 10199,
  735: 10771,
  736: 3512,
  737: 137094,
  738: 274479,
  739: 267860,
  740: 8078,
  741: 7485,
  742: 170687,
  743: 6435,
  744: 137106,
  745: 10040,
  746: 6278,
  747: 82682,
  748: 17610,
  749: 22954,
  750: 16995,
  751: 16558,
  752: 9849,
  753: 5820,
  754: 16866,
  755: 201,
  756: 11775,
  757: 87825,
  758: 12201,
  759: 11015,
  760: 9932,
  761: 13389,
  762: 8838,
  763: 17332,
  764: 4958,
  765: 786,
  766: 9513,
  767: 11679,
  768: 38321,
  769: 14411,
  770: 8413,
  771: 10052,
  772: 9676,
  773: 9664,
  774: 2100,
  775: 10384,
  776: 137321,
  777: 123553,
  778: 11260,
  779: 9009,
  780: 11374,
  781: 2309,
  782: 8285,
  783: 210860,
  784: 2312,
  785: 9839,
  786: 381902,
  787: 13922,
  788: 293660,
  789: 9713,
  790: 190859,
  791: 257445,
  792: 9007,
  793: 889,
  794: 1370,
  795: 4942,
  796: 347969,
  797: 24438,
  798: 116741,
  799: 35791,
  800: 72431,
  801: 1813,
  802: 87428,
  803: 8840,
  804: 10589,
  805: 71676,
  806: 1722,
  807: 10022,
  808: 11358,
  809: 13,
  810: 6477,
  811: 1597,
  812: 10530,
  813: 1924,
  814: 9327,
  815: 8488,
  816: 10603,
  817: 8273,
  818: 109424,
  819: 35056,
  820: 8839,
  821: 156022,
  822: 7303,
  823: 8963,
  824: 1402,
  825: 9315,
  826: 8984,
  827: 795,
  828: 24,
  829: 11353,
  830: 393,
  831: 9618,
  832: 9374,
  833: 8584,
  834: 2320,
  835: 58224,
  836: 1729,
  837: 175574,
  838: 8077,
  839: 8818,
  840: 8195,
  841: 10586,
  842: 116149,
  843: 80035,
  844: 10632,
  845: 12117,
  846: 1792,
  847: 13260,
  848: 72197,
  849: 3580,
  850: 12123,
  851: 9566,
  852: 9833,
  853: 4517,
  854: 8202,
  855: 16072,
  856: 34314,
  857: 19724,
  858: 145220,
  859: 14623,
  860: 42297,
  861: 2841,
  862: 802,
  863: 10375,
  864: 36586,
  865: 11321,
  866: 70074,
  867: 242,
  868: 9621,
  869: 1819,
  870: 8536,
  871: 8046,
  872: 1717,
  873: 479,
  874: 9444,
  875: 824,
  876: 11456,
  877: 261023,
  878: 3683,
  879: 22803,
  880: 285923,
  881: 39437,
  882: 1950,
  883: 640,
  884: 97630,
  885: 9767,
  886: 11631,
  887: 32856,
  888: 6519,
  889: 8741,
  890: 49520,
  891: 1850,
  892: 524,
  893: 26389,
  894: 11817,
  895: 2123,
  896: 9907,
  897: 9969,
  898: 18239,
  899: 808,
  900: 38050,
  901: 8367,
  902: 9390,
  903: 72105,
  904: 2898,
  905: 10312,
  906: 109443,
  907: 2022,
  908: 37686,
  909: 462,
  910: 9919,
  911: 187017,
  912: 628,
  913: 10201,
  914: 302699,
  915: 9441,
  916: 274167,
  917: 224141,
  918: 388,
  919: 2112,
  920: 10329,
  921: 74465,
  922: 13811,
  923: 6877,
  924: 10320,
  925: 50646,
  926: 8920,
  927: 13673,
  928: 60308,
  929: 6950,
  930: 225574,
  931: 13836,
  932: 752,
  933: 6038,
  934: 9975,
  935: 11451,
  936: 12103,
  937: 60304,
  938: 2251,
  939: 46529,
  940: 231,
  941: 300671,
  942: 228326,
  943: 9754,
  944: 66,
  945: 4421,
  946: 2649,
  947: 588,
  948: 10393,
  949: 71552,
  950: 9631,
  951: 216282,
  952: 306,
  953: 928,
  954: 205587,
  955: 6623,
  956: 1577,
  957: 9801,
  958: 2116,
  959: 9624,
  960: 14199,
  961: 1907,
  962: 4599,
  963: 22832,
  964: 10390,
  965: 9879,
  966: 38579,
  967: 44603,
  968: 11892,
  969: 9691,
  970: 1248,
  971: 12220,
  972: 72710,
  973: 1255,
  974: 10782,
  975: 9573,
  976: 4959,
  977: 10061,
  978: 10386,
  979: 421,
  980: 316152,
  981: 11615,
  982: 13498,
  983: 241554,
  984: 2252,
  985: 11968,
  986: 10047,
  987: 38319,
  988: 69668,
  989: 9770,
  990: 11212,
  991: 10533,
  992: 38363,
  993: 9923,
  994: 11863,
  995: 18501,
  996: 109491,
  997: 9275,
  998: 329833,
  999: 12634,
  ...},
 'title': {0: 'Avatar',
  1: "Pirates of the Caribbean: At World's End",
  2: 'Spectre',
  3: 'The Dark Knight Rises',
  4: 'John Carter',
  5: 'Spider-Man 3',
  6: 'Tangled',
  7: 'Avengers: Age of Ultron',
  8: 'Harry Potter and the Half-Blood Prince',
  9: 'Batman v Superman: Dawn of Justice',
  10: 'Superman Returns',
  11: 'Quantum of Solace',
  12: "Pirates of the Caribbean: Dead Man's Chest",
  13: 'The Lone Ranger',
  14: 'Man of Steel',
  15: 'The Chronicles of Narnia: Prince Caspian',
  16: 'The Avengers',
  17: 'Pirates of the Caribbean: On Stranger Tides',
  18: 'Men in Black 3',
  19: 'The Hobbit: The Battle of the Five Armies',
  20: 'The Amazing Spider-Man',
  21: 'Robin Hood',
  22: 'The Hobbit: The Desolation of Smaug',
  23: 'The Golden Compass',
  24: 'King Kong',
  25: 'Titanic',
  26: 'Captain America: Civil War',
  27: 'Battleship',
  28: 'Jurassic World',
  29: 'Skyfall',
  30: 'Spider-Man 2',
  31: 'Iron Man 3',
  32: 'Alice in Wonderland',
  33: 'X-Men: The Last Stand',
  34: 'Monsters University',
  35: 'Transformers: Revenge of the Fallen',
  36: 'Transformers: Age of Extinction',
  37: 'Oz: The Great and Powerful',
  38: 'The Amazing Spider-Man 2',
  39: 'TRON: Legacy',
  40: 'Cars 2',
  41: 'Green Lantern',
  42: 'Toy Story 3',
  43: 'Terminator Salvation',
  44: 'Furious 7',
  45: 'World War Z',
  46: 'X-Men: Days of Future Past',
  47: 'Star Trek Into Darkness',
  48: 'Jack the Giant Slayer',
  49: 'The Great Gatsby',
  50: 'Prince of Persia: The Sands of Time',
  51: 'Pacific Rim',
  52: 'Transformers: Dark of the Moon',
  53: 'Indiana Jones and the Kingdom of the Crystal Skull',
  54: 'The Good Dinosaur',
  55: 'Brave',
  56: 'Star Trek Beyond',
  57: 'WALL·E',
  58: 'Rush Hour 3',
  59: '2012',
  60: 'A Christmas Carol',
  61: 'Jupiter Ascending',
  62: 'The Legend of Tarzan',
  63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  64: 'X-Men: Apocalypse',
  65: 'The Dark Knight',
  66: 'Up',
  67: 'Monsters vs Aliens',
  68: 'Iron Man',
  69: 'Hugo',
  70: 'Wild Wild West',
  71: 'The Mummy: Tomb of the Dragon Emperor',
  72: 'Suicide Squad',
  73: 'Evan Almighty',
  74: 'Edge of Tomorrow',
  75: 'Waterworld',
  76: 'G.I. Joe: The Rise of Cobra',
  77: 'Inside Out',
  78: 'The Jungle Book',
  79: 'Iron Man 2',
  80: 'Snow White and the Huntsman',
  81: 'Maleficent',
  82: 'Dawn of the Planet of the Apes',
  83: 'The Lovers',
  84: '47 Ronin',
  85: 'Captain America: The Winter Soldier',
  86: 'Shrek Forever After',
  87: 'Tomorrowland',
  88: 'Big Hero 6',
  89: 'Wreck-It Ralph',
  90: 'The Polar Express',
  91: 'Independence Day: Resurgence',
  92: 'How to Train Your Dragon',
  93: 'Terminator 3: Rise of the Machines',
  94: 'Guardians of the Galaxy',
  95: 'Interstellar',
  96: 'Inception',
  97: 'Shin Godzilla',
  98: 'The Hobbit: An Unexpected Journey',
  99: 'The Fast and the Furious',
  100: 'The Curious Case of Benjamin Button',
  101: 'X-Men: First Class',
  102: 'The Hunger Games: Mockingjay - Part 2',
  103: "The Sorcerer's Apprentice",
  104: 'Poseidon',
  105: 'Alice Through the Looking Glass',
  106: 'Shrek the Third',
  107: 'Warcraft',
  108: 'Terminator Genisys',
  109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
  110: 'Pearl Harbor',
  111: 'Transformers',
  112: 'Alexander',
  113: 'Harry Potter and the Order of the Phoenix',
  114: 'Harry Potter and the Goblet of Fire',
  115: 'Hancock',
  116: 'I Am Legend',
  117: 'Charlie and the Chocolate Factory',
  118: 'Ratatouille',
  119: 'Batman Begins',
  120: 'Madagascar: Escape 2 Africa',
  121: 'Night at the Museum: Battle of the Smithsonian',
  122: 'X-Men Origins: Wolverine',
  123: 'The Matrix Revolutions',
  124: 'Frozen',
  125: 'The Matrix Reloaded',
  126: 'Thor: The Dark World',
  127: 'Mad Max: Fury Road',
  128: 'Angels & Demons',
  129: 'Thor',
  130: 'Bolt',
  131: 'G-Force',
  132: 'Wrath of the Titans',
  133: 'Dark Shadows',
  134: 'Mission: Impossible - Rogue Nation',
  135: 'The Wolfman',
  136: 'Bee Movie',
  137: 'Kung Fu Panda 2',
  138: 'The Last Airbender',
  139: 'Mission: Impossible III',
  140: 'White House Down',
  141: 'Mars Needs Moms',
  142: 'Flushed Away',
  143: 'Pan',
  144: 'Mr. Peabody & Sherman',
  145: 'Troy',
  146: "Madagascar 3: Europe's Most Wanted",
  147: 'Die Another Day',
  148: 'Ghostbusters',
  149: 'Armageddon',
  150: 'Men in Black II',
  151: 'Beowulf',
  152: 'Kung Fu Panda 3',
  153: 'Mission: Impossible - Ghost Protocol',
  154: 'Rise of the Guardians',
  155: 'Fun with Dick and Jane',
  156: 'The Last Samurai',
  157: 'Exodus: Gods and Kings',
  158: 'Star Trek',
  159: 'Spider-Man',
  160: 'How to Train Your Dragon 2',
  161: 'Gods of Egypt',
  162: 'Stealth',
  163: 'Watchmen',
  164: 'Lethal Weapon 4',
  165: 'Hulk',
  166: 'G.I. Joe: Retaliation',
  167: 'Sahara',
  168: 'Final Fantasy: The Spirits Within',
  169: 'Captain America: The First Avenger',
  170: 'The World Is Not Enough',
  171: 'Master and Commander: The Far Side of the World',
  172: 'The Twilight Saga: Breaking Dawn - Part 2',
  173: 'Happy Feet Two',
  174: 'The Incredible Hulk',
  175: 'The BFG',
  176: 'The Revenant',
  177: 'Turbo',
  178: 'Rango',
  179: 'Penguins of Madagascar',
  180: 'The Bourne Ultimatum',
  181: 'Kung Fu Panda',
  182: 'Ant-Man',
  183: 'The Hunger Games: Catching Fire',
  184: 'Home',
  185: 'War of the Worlds',
  186: 'Bad Boys II',
  187: 'Puss in Boots',
  188: 'Salt',
  189: 'Noah',
  190: 'The Adventures of Tintin',
  191: 'Harry Potter and the Prisoner of Azkaban',
  192: 'Australia',
  193: 'After Earth',
  194: 'Dinosaur',
  195: 'Night at the Museum: Secret of the Tomb',
  196: 'Megamind',
  197: "Harry Potter and the Philosopher's Stone",
  198: 'R.I.P.D.',
  199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
  200: 'The Hunger Games: Mockingjay - Part 1',
  201: 'The Da Vinci Code',
  202: 'Rio 2',
  203: 'X2',
  204: 'Fast Five',
  205: 'Sherlock Holmes: A Game of Shadows',
  206: 'Clash of the Titans',
  207: 'Total Recall',
  208: 'The 13th Warrior',
  209: 'The Bourne Legacy',
  210: 'Batman & Robin',
  211: 'How the Grinch Stole Christmas',
  212: 'The Day After Tomorrow',
  213: 'Mission: Impossible II',
  214: 'The Perfect Storm',
  215: 'Fantastic 4: Rise of the Silver Surfer',
  216: 'Life of Pi',
  217: 'Ghost Rider',
  218: 'Jason Bourne',
  219: "Charlie's Angels: Full Throttle",
  220: 'Prometheus',
  221: 'Stuart Little 2',
  222: 'Elysium',
  223: 'The Chronicles of Riddick',
  224: 'RoboCop',
  225: 'Speed Racer',

In [ ]:
similarity

array([[1.        , 0.8416873 , 0.65264908, ..., 0.55533223, 0.01855177,
        0.39379375],
       [0.8416873 , 1.        , 0.64219492, ..., 0.55481575, 0.        ,
        0.39452673],
       [0.65264908, 0.64219492, 1.        , ..., 0.42786599, 0.0562878 ,
        0.29870172],
       ...,
       [0.55533223, 0.55481575, 0.42786599, ..., 1.        , 0.02828427,
        0.27874926],
       [0.01855177, 0.        , 0.0562878 , ..., 0.02828427, 1.        ,
        0.06064784],
       [0.39379375, 0.39452673, 0.29870172, ..., 0.27874926, 0.06064784,
        1.        ]])

In [ ]:
pickle.dump(df.to_dict(),open('movie_dict.pkl', mode='wb'))

In [ ]:
pickle.dump(similarity, open('similarity.pkl', mode='wb'))

In [ ]:
df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

In [ ]:
list(df['title'].values)

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',
 'TRON: Legacy',
 'Cars 2',
 'Green Lantern',
 'Toy Story 3',
 'Terminator Salvation',
 'Furious 7',
 'World War Z',
 'X-Men: Days of Future Past',
 'Star Trek Into Darkness',
 'Jack the Giant Slayer',
 'The Great Gatsby',
 'Prince of Persia: The Sands of Time',
 'Pacific Rim',
 'Transformers: Dark of the Moon',
 'Indiana Jones and the Kingdom of the Crystal Skull',
 'The Good Dinosaur',
 'Brave',
 'Star Trek Beyond',
 'WALL·E',
 'Rush Hour 3',
 '2012',
 'A Christmas Carol',
 'Jupiter Ascending',
 'The Legend of Tarzan',
 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 'X-Men: Apocalypse',
 'The Dark Knight',
 'Up',
 'Monsters vs Aliens',
 'Iron Man',
 'Hugo',
 'Wild Wild West',
 'The Mummy: Tomb of the Dragon Emperor',
 'Suicide Squad',
 'Evan Almighty',
 'Edge of Tomorrow',
 'Waterworld',
 'G.I. Joe: The Rise of Cobra',
 'Inside Out',
 'The Jungle Book',
 'Iron Man 2',
 'Snow White and the Huntsman',
 'Maleficent',
 'Dawn of the Planet of the Apes',
 'The Lovers',
 '47 Ronin',
 'Captain America: The Winter Soldier',
 'Shrek Forever After',
 'Tomorrowland',
 'Big Hero 6',
 'Wreck-It Ralph',
 'The Polar Express',
 'Independence Day: Resurgence',
 'How to Train Your Dragon',
 'Terminator 3: Rise of the Machines',
 'Guardians of the Galaxy',
 'Interstellar',
 'Inception',
 'Shin Godzilla',
 'The Hobbit: An Unexpected Journey',
 'The Fast and the Furious',
 'The Curious Case of Benjamin Button',
 'X-Men: First Class',
 'The Hunger Games: Mockingjay - Part 2',
 "The Sorcerer's Apprentice",
 'Poseidon',
 'Alice Through the Looking Glass',
 'Shrek the Third',
 'Warcraft',
 'Terminator Genisys',
 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 'Pearl Harbor',
 'Transformers',
 'Alexander',
 'Harry Potter and the Order of the Phoenix',
 'Harry Potter and the Goblet of Fire',
 'Hancock',
 'I Am Legend',
 'Charlie and the Chocolate Factory',
 'Ratatouille',
 'Batman Begins',
 'Madagascar: Escape 2 Africa',
 'Night at the Museum: Battle of the Smithsonian',
 'X-Men Origins: Wolverine',
 'The Matrix Revolutions',
 'Frozen',
 'The Matrix Reloaded',
 'Thor: The Dark World',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Thor',
 'Bolt',
 'G-Force',
 'Wrath of the Titans',
 'Dark Shadows',
 'Mission: Impossible - Rogue Nation',
 'The Wolfman',
 'Bee Movie',
 'Kung Fu Panda 2',
 'The Last Airbender',
 'Mission: Impossible III',
 'White House Down',
 'Mars Needs Moms',
 'Flushed Away',
 'Pan',
 'Mr. Peabody & Sherman',
 'Troy',
 "Madagascar 3: Europe's Most Wanted",
 'Die Another Day',
 'Ghostbusters',
 'Armageddon',
 'Men in Black II',
 'Beowulf',
 'Kung Fu Panda 3',
 'Mission: Impossible - Ghost Protocol',
 'Rise of the Guardians',
 'Fun with Dick and Jane',
 'The Last Samurai',
 'Exodus: Gods and Kings',
 'Star Trek',
 'Spider-Man',
 'How to Train Your Dragon 2',
 'Gods of Egypt',
 'Stealth',
 'Watchmen',
 'Lethal Weapon 4',
 'Hulk',
 'G.I. Joe: Retaliation',
 'Sahara',
 'Final Fantasy: The Spirits Within',
 'Captain America: The First Avenger',
 'The World Is Not Enough',
 'Master and Commander: The Far Side of the World',
 'The Twilight Saga: Breaking Dawn - Part 2',
 'Happy Feet Two',
 'The Incredible Hulk',
 'The BFG',
 'The Revenant',
 'Turbo',
 'Rango',
 'Penguins of Madagascar',
 'The Bourne Ultimatum',
 'Kung Fu Panda',
 'Ant-Man',
 'The Hunger Games: Catching Fire',
 'Home',
 'War of the Worlds',
 'Bad Boys II',
 'Puss in Boots',
 'Salt',
 'Noah',
 'The Adventures of Tintin',
 'Harry Potter and the Prisoner of Azkaban',
 'Australia',
 'After Earth',
 'Dinosaur',
 'Night at the Museum: Secret of the Tomb',
 'Megamind',
 "Harry Potter and the Philosopher's Stone",
 'R.I.P.D.',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'The Hunger Games: Mockingjay - Part 1',
 'The Da Vinci Code',
 'Rio 2',
 'X2',
 'Fast Five',
 'Sherlock Holmes: A Game of Shadows',
 'Clash of the Titans',
 'Total Recall',
 'The 13th Warrior',
 'The Bourne Legacy',
 'Batman & Robin',
 'How the Grinch Stole Christmas',
 'The Day After Tomorrow',
 'Mission: Impossible II',
 'The Perfect Storm',
 'Fantastic 4: Rise of the Silver Surfer',
 'Life of Pi',
 'Ghost Rider',
 'Jason Bourne',
 "Charlie's Angels: Full Throttle",
 'Prometheus',
 'Stuart Little 2',
 'Elysium',
 'The Chronicles of Riddick',
 'RoboCop',
 'Speed Racer',
 'How Do You Know',
 'Knight and Day',
 'Oblivion',
 'Star Wars: Episode III - Revenge of the Sith',
 'Star Wars: Episode II - Attack of the Clones',
 'Monsters, Inc.',
 'The Wolverine',
 'Star Wars: Episode I - The Phantom Menace',
 'The Croods',
 'Asterix at the Olympic Games',
 'Windtalkers',
 "The Huntsman: Winter's War",
 'Teenage Mutant Ninja Turtles',
 'Gravity',
 "Dante's Peak",
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Fantastic Four',
 'Night at the Museum',
 'San Andreas',
 'Tomorrow Never Dies',
 'The Patriot',
 "Ocean's Twelve",
 'Mr. & Mrs. Smith',
 'Insurgent',
 'The Aviator',
 "Gulliver's Travels",
 'The Green Hornet',
 '300: Rise of an Empire',
 'The Smurfs',
 'Home on the Range',
 'Allegiant',
 'Real Steel',
 'The Smurfs 2',
 'Speed 2: Cruise Control',
 "Ender's Game",
 'Live Free or Die Hard',
 'The Lord of the Rings: The Fellowship of the Ring',
 'Around the World in 80 Days',
 'Ali',
 'The Cat in the Hat',
 'I, Robot',
 'Kingdom of Heaven',
 'Stuart Little',
 'The Princess and the Frog',
 'The Martian',
 'The Island',
 'Town & Country',
 'Gone in Sixty Seconds',
 'Gladiator',
 'Minority Report',
 'Harry Potter and the Chamber of Secrets',
 'Casino Royale',
 'Planet of the Apes',
 'Terminator 2: Judgment Day',
 'Public Enemies',
 'American Gangster',
 'True Lies',
 'The Taking of Pelham 1 2 3',
 'Little Fockers',
 'The Other Guys',
 'Eraser',
 'Django Unchained',
 'The Hunchback of Notre Dame',
 "The Emperor's New Groove",
 'The Expendables 2',
 'National Treasure',
 'Eragon',
 'Where the Wild Things Are',
 'Epic',
 'The Tourist',
 'End of Days',
 'Blood Diamond',
 'The Wolf of Wall Street',
 'Batman Forever',
 'Starship Troopers',
 'Cloud Atlas',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'Catwoman',
 'Hercules',
 'Treasure Planet',
 'Land of the Lost',
 'The Expendables 3',
 'Point Break',
 'Son of the Mask',
 'In the Heart of the Sea',
 'The Adventures of Pluto Nash',
 'Green Zone',
 'The Peanuts Movie',
 'The Spanish Prisoner',
 'The Mummy Returns',
 'Gangs of New York',
 'The Flowers of War',
 "Surf's Up",
 'The Stepford Wives',
 'Black Hawk Down',
 'The Campaign',
 'The Fifth Element',
 'Sex and the City 2',
 'The Road to El Dorado',
 'Ice Age: Continental Drift',
 'Cinderella',
 'The Lovely Bones',
 'Finding Nemo',
 'The Lord of the Rings: The Return of the King',
 'The Lord of the Rings: The Two Towers',
 'Seventh Son',
 'Lara Croft: Tomb Raider',
 'Transcendence',
 'Jurassic Park III',
 'Rise of the Planet of the Apes',
 'The Spiderwick Chronicles',
 'A Good Day to Die Hard',
 'The Alamo',
 'The Incredibles',
 'Cutthroat Island',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'Men in Black',
 'Toy Story 2',
 'Unstoppable',
 'Rush Hour 2',
 'What Lies Beneath',
 'Cloudy with a Chance of Meatballs',
 'Ice Age: Dawn of the Dinosaurs',
 'The Secret Life of Walter Mitty',
 "Charlie's Angels",
 'The Departed',
 'Mulan',
 'Tropic Thunder',
 'The Girl with the Dragon Tattoo',
 'Die Hard: With a Vengeance',
 'Sherlock Holmes',
 'Ben-Hur',
 'Atlantis: The Lost Empire',
 'Alvin and the Chipmunks: The Road Chip',
 'Valkyrie',
 "You Don't Mess with the Zohan",
 'Pixels',
 'A.I. Artificial Intelligence',
 'The Haunted Mansion',
 'Contact',
 'Hollow Man',
 'The Interpreter',
 'Percy Jackson: Sea of Monsters',
 'Lara Croft Tomb Raider: The Cradle of Life',
 'Now You See Me 2',
 'The Saint',
 'Spy Game',
 'Mission to Mars',
 'Rio',
 'Bicentennial Man',
 'Volcano',
 "The Devil's Own",
 'K-19: The Widowmaker',
 'Conan the Barbarian',
 'Cinderella Man',
 'The Nutcracker: The Untold Story',
 'Seabiscuit',
 'Twister',
 'Cast Away',
 'Happy Feet',
 'The Bourne Supremacy',
 'Air Force One',
 "Ocean's Eleven",
 'The Three Musketeers',
 'Hotel Transylvania',
 'Enchanted',
 'Safe House',
 '102 Dalmatians',
 'Tower Heist',
 'The Holiday',
 'Enemy of the State',
 "It's Complicated",
 "Ocean's Thirteen",
 'Open Season',
 'Divergent',
 'Enemy at the Gates',
 'The Rundown',
 'Last Action Hero',
 'Memoirs of a Geisha',
 'The Fast and the Furious: Tokyo Drift',
 'Arthur Christmas',
 'Meet Joe Black',
 'Collateral Damage',
 'All That Jazz',
 'Mirror Mirror',
 'Scott Pilgrim vs. the World',
 'The Core',
 'Nutty Professor II: The Klumps',
 'Scooby-Doo',
 'Dredd',
 'Click',
 'Creepshow',
 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 'Jumper',
 'Hellboy II: The Golden Army',
 'Zodiac',
 'The 6th Day',
 'Bruce Almighty',
 'The Expendables',
 'Mission: Impossible',
 'The Hunger Games',
 'The Hangover Part II',
 'Batman Returns',
 'Over the Hedge',
 'Lilo & Stitch',
 "Charlotte's Web",
 'Deep Impact',
 'RED 2',
 'The Longest Yard',
 'Alvin and the Chipmunks: Chipwrecked',
 'Grown Ups 2',
 'Get Smart',
 "Something's Gotta Give",
 'Shutter Island',
 'Four Christmases',
 'Robots',
 'Face/Off',
 'Bedtime Stories',
 'Road to Perdition',
 'Just Go with It',
 'Con Air',
 'Eagle Eye',
 'Cold Mountain',
 'The Book of Eli',
 'Flubber',
 'The Haunting',
 'Space Jam',
 'The Pink Panther',
 'The Day the Earth Stood Still',
 'Conspiracy Theory',
 'Fury',
 'Six Days Seven Nights',
 'Yogi Bear',
 'Spirit: Stallion of the Cimarron',
 'Zookeeper',
 'Lost in Space',
 'The Manchurian Candidate',
 'Déjà Vu',
 'Hotel Transylvania 2',
 'Fantasia 2000',
 'The Time Machine',
 'Mighty Joe Young',
 'Swordfish',
 'The Legend of Zorro',
 'What Dreams May Come',
 'Little Nicky',
 'The Brothers Grimm',
 'Mars Attacks!',
 'Evolution',
 'The Edge',
 'Surrogates',
 'Thirteen Days',
 'Daylight',
 'Walking With Dinosaurs',
 'Battlefield Earth',
 'Looney Tunes: Back in Action',
 'Nine',
 'Timeline',
 'The Postman',
 'Babe: Pig in the City',
 'The Last Witch Hunter',
 'Red Planet',
 'Arthur and the Invisibles',
 'Oceans',
 'A Sound of Thunder',
 'Pompeii',
 'Top Cat Begins',
 'A Beautiful Mind',
 'The Lion King',
 'Journey 2: The Mysterious Island',
 'Cloudy with a Chance of Meatballs 2',
 'Red Dragon',
 'Hidalgo',
 'Jack and Jill',
 '2 Fast 2 Furious',
 'The Little Prince',
 'The Invasion',
 'The Adventures of Rocky & Bullwinkle',
 'The Secret Life of Pets',
 'The League of Extraordinary Gentlemen',
 'Despicable Me 2',
 'Independence Day',
 'The Lost World: Jurassic Park',
 'Madagascar',
 'Children of Men',
 'X-Men',
 'Wanted',
 'The Rock',
 'Ice Age: The Meltdown',
 '50 First Dates',
 'Hairspray',
 'Exorcist: The Beginning',
 'Inspector Gadget',
 'Now You See Me',
 'Grown Ups',
 'The Terminal',
 'Hotel for Dogs',
 'Vertical Limit',
 "Charlie Wilson's War",
 'Shark Tale',
 'Dreamgirls',
 'Be Cool',
 'Munich',
 'Tears of the Sun',
 'Killers',
 'The Man from U.N.C.L.E.',
 'Spanglish',
 'Monster House',
 'Bandits',
 'First Knight',
 'Anna and the King',
 'Immortals',
 'Hostage',
 'Titan A.E.',
 'Hollywood Homicide',
 'Soldier',
 'Carriers',
 'Monkeybone',
 'Flight of the Phoenix',
 'Unbreakable',
 'Minions',
 'Sucker Punch',
 'Snake Eyes',
 'Sphere',
 'The Angry Birds Movie',
 "Fool's Gold",
 'Funny People',
 'The Kingdom',
 'Talladega Nights: The Ballad of Ricky Bobby',
 'Dr. Dolittle 2',
 'Braveheart',
 'Jarhead',
 'The Simpsons Movie',
 'The Majestic',
 'Driven',
 'Two Brothers',
 'The Village',
 'Doctor Dolittle',
 'Signs',
 'Shrek 2',
 'Cars',
 'Runaway Bride',
 'xXx',
 'The SpongeBob Movie: Sponge Out of Water',
 'Ransom',
 'Inglourious Basterds',
 'Hook',
 'Die Hard 2',
 'S.W.A.T.',
 'Vanilla Sky',
 'Lady in the Water',
 'AVP: Alien vs. Predator',
 'Alvin and the Chipmunks: The Squeakquel',
 'We Were Soldiers',
 'Olympus Has Fallen',
 'Star Trek: Insurrection',
 'Battle: Los Angeles',
 'Big Fish',
 'Wolf',
 'War Horse',
 'The Monuments Men',
 'The Abyss',
 'Wall Street: Money Never Sleeps',
 'Dracula Untold',
 'The Siege',
 'Stardust',
 'Seven Years in Tibet',
 'The Dilemma',
 'Bad Company',
 'Doom',
 'I Spy',
 'Underworld: Awakening',
 'Rock of Ages',
 "Hart's War",
 'Killer Elite',
 'Rollerball',
 'Ballistic: Ecks vs. Sever',
 'Hard Rain',
 'Osmosis Jones',
 "Legends of Oz: Dorothy's Return",
 'Blackhat',
 'Sky Captain and the World of Tomorrow',
 'Basic Instinct 2',
 'Escape Plan',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'The Twilight Saga: Eclipse',
 'The Score',
 'Despicable Me',
 'Money Train',
 'Ted 2',
 'Agora',
 'Mystery Men',
 'Hall Pass',
 'The Insider',
 'The Finest Hours',
 'Body of Lies',
 'Dinner for Schmucks',
 'Abraham Lincoln: Vampire Hunter',
 'Entrapment',
 'The X Files',
 'The Last Legion',
 'Saving Private Ryan',
 'Need for Speed',
 'What Women Want',
 'Ice Age',
 'Dreamcatcher',
 'Lincoln',
 'The Matrix',
 'Apollo 13',
 'The Santa Clause 2',
 'Les Misérables',
 "You've Got Mail",
 'Step Brothers',
 'The Mask of Zorro',
 'Due Date',
 'Unbroken',
 'Space Cowboys',
 'Cliffhanger',
 'Broken Arrow',
 'The Kid',
 'World Trade Center',
 'Mona Lisa Smile',
 'The Dictator',
 'Eyes Wide Shut',
 'Annie',
 'Focus',
 'This Means War',
 'Blade: Trinity',
 'Red Dawn',
 'Primary Colors',
 'Resident Evil: Retribution',
 'Death Race',
 'The Long Kiss Goodnight',
 'Proof of Life',
 'Zathura: A Space Adventure',
 'Fight Club',
 'We Are Marshall',
 'Hudson Hawk',
 'Lucky Numbers',
 'I, Frankenstein',
 'Oliver Twist',
 'Elektra',
 'Sin City: A Dame to Kill For',
 'Random Hearts',
 'Everest',
 'Perfume: The Story of a Murderer',
 'Austin Powers in Goldmember',
 'Astro Boy',
 'Jurassic Park',
 'Wyatt Earp',
 'Clear and Present Danger',
 'Dragon Blade',
 'Little Man',
 'U-571',
 'The American President',
 'The Love Guru',
 '3000 Miles to Graceland',
 'The Hateful Eight',
 'Blades of Glory',
 'Hop',
 '300',
 'Meet the Fockers',
 'Marley & Me',
 'The Green Mile',
 'Wild Hogs',
 'Chicken Little',
 'Gone Girl',
 'The Bourne Identity',
 'GoldenEye',
 "The General's Daughter",
 'The Truman Show',
 'The Prince of Egypt',
 'Daddy Day Care',
 '2 Guns',
 'Cats & Dogs',
 'The Italian Job',
 'Two Weeks Notice',
 'Antz',
 'Couples Retreat',
 'Days of Thunder',
 'Cheaper by the Dozen 2',
 'Maze Runner: The Scorch Trials',
 'Eat Pray Love',
 'The Family Man',
 'RED',
 'Any Given Sunday',
 'The Horse Whisperer',
 'Collateral',
 'The Scorpion King',
 'Ladder 49',
 'Jack Reacher',
 'Deep Blue Sea',
 'This Is It',
 'Contagion',
 'Kangaroo Jack',
 'Coraline',
 'The Happening',
 'Man on Fire',
 'The Shaggy Dog',
 'Starsky & Hutch',
 'Jingle All the Way',
 'Hellboy',
 'A Civil Action',
 'ParaNorman',
 'The Jackal',
 'Paycheck',
 'Up Close & Personal',
 'The Tale of Despereaux',
 'The Tuxedo',
 'Under Siege 2: Dark Territory',
 'Jack Ryan: Shadow Recruit',
 'Joy',
 'London Has Fallen',
 'Alien: Resurrection',
 'Shooter',
 'The Boxtrolls',
 'Practical Magic',
 'The Lego Movie',
 'Miss Congeniality 2: Armed and Fabulous',
 'Reign of Fire',
 'Gangster Squad',
 'Year One',
 'Invictus',
 'State of Play',
 'Duplicity',
 'My Favorite Martian',
 'The Sentinel',
 'Planet 51',
 'Star Trek: Nemesis',
 'Intolerable Cruelty',
 'Trouble with the Curve',
 'Edge of Darkness',
 'The Relic',
 'Analyze That',
 'Righteous Kill',
 'Mercury Rising',
 'The Soloist',
 'The Legend of Bagger Vance',
 'Almost Famous',
 'Garfield: A Tail of Two Kitties',
 'xXx: State of the Union',
 'Priest',
 'Sinbad: Legend of the Seven Seas',
 'Event Horizon',
 'Dragonfly',
 'The Black Dahlia',
 'Flyboys',
 'The Last Castle',
 'Supernova',
 "Winter's Tale",
 'The Mortal Instruments: City of Bones',
 'Meet Dave',
 'Dark Water',
 'Edtv',
 'Inkheart',
 'The Spirit',
 'Mortdecai',
 'In the Name of the King: A Dungeon Siege Tale',
 'Beyond Borders',
 'The Monkey King 2',
 'The Great Raid',
 'Deadpool',
 'Holy Man',
 'American Sniper',
 'Goosebumps',
 'Just Like Heaven',
 'The Flintstones in Viva Rock Vegas',
 'Rambo III',
 'Leatherheads',
 'The Ridiculous 6',
 'Did You Hear About the Morgans?',
 'The Internship',
 'Resident Evil: Afterlife',
 'Red Tails',
 "The Devil's Advocate",
 "That's My Boy",
 'DragonHeart',
 'After the Sunset',
 'Ghost Rider: Spirit of Vengeance',
 "Captain Corelli's Mandolin",
 'The Pacifier',
 'Walking Tall',
 'Forrest Gump',
 'Alvin and the Chipmunks',
 'Meet the Parents',
 'Pocahontas',
 'Superman',
 'The Nutty Professor',
 'Hitch',
 'George of the Jungle',
 'American Wedding',
 'Captain Phillips',
 'Date Night',
 'Casper',
 'The Equalizer',
 'Maid in Manhattan',
 'Crimson Tide',
 'The Pursuit of Happyness',
 'Flightplan',
 'Disclosure',
 'City of Angels',
 'Kill Bill: Vol. 1',
 'Bowfinger',
 'Kill Bill: Vol. 2',
 'Tango & Cash',
 'Death Becomes Her',
 'Shanghai Noon',
 'Executive Decision',
 "Mr. Popper's Penguins",
 'The Forbidden Kingdom',
 'Free Birds',
 'Alien³',
 'Evita',
 'Ronin',
 'The Ghost and the Darkness',
 'Paddington',
 'The Watch',
 'The Hunted',
 'Instinct',
 'Stuck on You',
 'Semi-Pro',
 'The Pirates! In an Adventure with Scientists!',
 'Changeling',
 'Chain Reaction',
 'The Fan',
 'The Phantom of the Opera',
 'Elizabeth: The Golden Age',
 'Æon Flux',
 'Gods and Generals',
 'Turbulence',
 'Imagine That',
 'Muppets Most Wanted',
 'Thunderbirds',
 'Burlesque',
 'A Very Long Engagement',
 'Lolita',
 'D-Tox',
 'Blade II',
 'Seven Pounds',
 'Bullet to the Head',
 'The Godfather: Part III',
 'Elizabethtown',
 'You, Me and Dupree',
 'Superman II',
 'Gigli',
 "All the King's Men",
 'Shaft',
 'Anastasia',
 'Moulin Rouge!',
 'Domestic Disturbance',
 'Black Mass',
 'Flags of Our Fathers',
 'Law Abiding Citizen',
 'Grindhouse',
 'Beloved',
 'Lucky You',
 'Catch Me If You Can',
 'Zero Dark Thirty',
 'The Break-Up',
 'Mamma Mia!',
 "Valentine's Day",
 'The Dukes of Hazzard',
 'The Thin Red Line',
 'The Change-Up',
 'Man on the Moon',
 'Casino',
 'From Paris with Love',
 'Bulletproof Monk',
 'Me, Myself & Irene',
 'Barnyard',
 'Deck the Halls',
 'The Twilight Saga: New Moon',
 'Shrek',
 'The Adjustment Bureau',
 'Robin Hood: Prince of Thieves',
 'Jerry Maguire',
 'Ted',
 'As Good as It Gets',
 'Patch Adams',
 'Anchorman 2: The Legend Continues',
 'Mr. Deeds',
 'Super 8',
 'Erin Brockovich',
 'How to Lose a Guy in 10 Days',
 '22 Jump Street',
 'Interview with the Vampire',
 'Yes Man',
 'Central Intelligence',
 'Stepmom',
 "Daddy's Home",
 'Into the Woods',
 'Inside Man',
 'Payback',
 'Congo',
 'We Bought a Zoo',
 'Knowing',
 'Failure to Launch',
 'The Ring Two',
 'Crazy, Stupid, Love.',
 'Garfield',
 'Christmas with the Kranks',
 'Moneyball',
 'Outbreak',
 'Non-Stop',
 'Race to Witch Mountain',
 'V for Vendetta',
 'Shanghai Knights',
 'Curious George',
 'Herbie Fully Loaded',
 "Don't Say a Word",
 'Hansel & Gretel: Witch Hunters',
 'Unfaithful',
 'I Am Number Four',
 'Syriana',
 '13 Hours: The Secret Soldiers of Benghazi',
 'The Book of Life',
 'Firewall',
 'Absolute Power',
 'G.I. Jane',
 'The Game',
 'Silent Hill',
 'The Replacements',
 'American Reunion',
 'The Negotiator',
 'Into the Storm',
 'Beverly Hills Cop III',
 'Gremlins 2: The New Batch',

Output of Movie recommendation system:-

In [ ]:
movie_name = input("Enter a movie name: ")
recommend(movie_name)

Enter a movie name: Iron Man
Iron Man 3
The Incredible Hulk
Fantastic 4: Rise of the Silver Surfer
Southland Tales
Hulk

Another Way :-

In [ ]:
import ipywidgets as widgets
from IPython.display import display

movie_dropdown = widgets.Dropdown(
    options=movies['title'].tolist(),
    description='Movie:'
)

display(movie_dropdown)

Dropdown(description='Movie:', options=('Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The …

In [ ]:
button = widgets.Button(description="Recommend")

def on_button_click(b):
    recommend(movie_dropdown.value)

button.on_click(on_button_click)

display(button)

Button(description='Recommend', style=ButtonStyle())

Iron Man 3
The Avengers
Iron Man
Thor
Captain America: Civil War